{
  "version": "4.28.0",
  "time": 221.241,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "480464ceabe78fe675c5d9e24c9dff23",
          "bytes": 56422263,
          "fields": 27,
          "rows": 1846544
        }
      },
      "time": 221.241,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44018",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "883",
            "61470",
            "1",
            "55",
            "422",
            "21789",
            "180905",
            "369612",
            "75482",
            "889",
            "1831986",
            "2744",
            "2046",
            "2022",
            "2022-05-20",
            "17.0000",
            "3180.0000",
            "54060.00",
            "3180.0000",
            "54060.00",
            "54060.00"
          ],
          "rowNumber": 1802108,
          "rowPosition": 1802109,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75482\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802109\" violates the foreign key: for \"id_contrato\": values \"75482\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44017",
            "14",
            "1831020",
            "50",
            "1",
            "8",
            "66",
            "71267",
            "1",
            "77",
            "719",
            "15485",
            "233944",
            "370806",
            "46296",
            "889",
            "1831369",
            "3144",
            "2839",
            "2022",
            "2022-06-08",
            "0.0000",
            "11746.9000",
            "11746.90",
            "11746.9000",
            "11746.90",
            "11746.90"
          ],
          "rowNumber": 1802472,
          "rowPosition": 1802473,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71267\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1802473\" violates the foreign key: for \"id_contratado\": values \"71267\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44017",
            "1",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "71266",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "370760",
            "46296",
            "889",
            "1831808",
            "3144",
            "1760",
            "2022",
            "2022-06-08",
            "0.0000",
            "17617.8900",
            "17617.89",
            "17617.8900",
            "17617.89",
            "17617.89"
          ],
          "rowNumber": 1802477,
          "rowPosition": 1802478,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71266\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1802478\" violates the foreign key: for \"id_contratado\": values \"71266\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43976",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "366826",
            "75465",
            "889",
            "1831295",
            "2611",
            "2046",
            "2022",
            "2022-04-07",
            "4.0000",
            "4921.1000",
            "19684.40",
            "4921.1000",
            "19684.40",
            "19684.40"
          ],
          "rowNumber": 1819504,
          "rowPosition": 1819505,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75465\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819505\" violates the foreign key: for \"id_contrato\": values \"75465\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "56257",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "369492",
            "75484",
            "889",
            "1831498",
            "2670",
            "3042",
            "2022",
            "2022-05-19",
            "0.0000",
            "28800.0000",
            "28800.00",
            "25920.0000",
            "25920.00",
            "25920.00"
          ],
          "rowNumber": 1827993,
          "rowPosition": 1827994,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827994\" violates the foreign key: for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "56257",
            "1",
            "57",
            "677",
            "521",
            "21899",
            "369492",
            "75484",
            "190",
            "1831313",
            "2585",
            "3042",
            "2022",
            "2022-05-19",
            "3000.0000",
            "8.3300",
            "24990.00",
            "8.1300",
            "24390.00",
            "24390.00"
          ],
          "rowNumber": 1827994,
          "rowPosition": 1827995,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827995\" violates the foreign key: for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "56257",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "369492",
            "75484",
            "889",
            "1831498",
            "2670",
            "3042",
            "2022",
            "2022-05-19",
            "0.0000",
            "28800.0000",
            "28800.00",
            "25920.0000",
            "25920.00",
            "25920.00"
          ],
          "rowNumber": 1827995,
          "rowPosition": 1827996,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827996\" violates the foreign key: for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "56257",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "369492",
            "75484",
            "889",
            "1831498",
            "2670",
            "3042",
            "2022",
            "2022-05-19",
            "0.0000",
            "28800.0000",
            "28800.00",
            "25920.0000",
            "25920.00",
            "25920.00"
          ],
          "rowNumber": 1827996,
          "rowPosition": 1827997,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827997\" violates the foreign key: for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "56257",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "369492",
            "75484",
            "889",
            "1831498",
            "2670",
            "3042",
            "2022",
            "2022-05-19",
            "0.0000",
            "36000.0000",
            "36000.00",
            "36000.0000",
            "36000.00",
            "36000.00"
          ],
          "rowNumber": 1827997,
          "rowPosition": 1827998,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827998\" violates the foreign key: for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "56257",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "369492",
            "75484",
            "889",
            "1831498",
            "2670",
            "3042",
            "2022",
            "2022-05-19",
            "0.0000",
            "28800.0000",
            "28800.00",
            "25920.0000",
            "25920.00",
            "25920.00"
          ],
          "rowNumber": 1827998,
          "rowPosition": 1827999,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827999\" violates the foreign key: for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "56257",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "369492",
            "75484",
            "889",
            "1831498",
            "2670",
            "3042",
            "2022",
            "2022-05-19",
            "0.0000",
            "28800.0000",
            "28800.00",
            "25920.0000",
            "25920.00",
            "25920.00"
          ],
          "rowNumber": 1827999,
          "rowPosition": 1828000,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828000\" violates the foreign key: for \"id_contrato\": values \"75484\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44022",
            "17",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "28939",
            "1",
            "89",
            "778",
            "7242",
            "231394",
            "369863",
            "75474",
            "889",
            "1831991",
            "3018",
            "3042",
            "2022",
            "2022-05-24",
            "150.0000",
            "8450.0000",
            "1267500.00",
            "8450.0000",
            "1267500.00",
            "1267500.00"
          ],
          "rowNumber": 1829601,
          "rowPosition": 1829602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75474\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829602\" violates the foreign key: for \"id_contrato\": values \"75474\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44022",
            "17",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "28939",
            "1",
            "44",
            "724",
            "15676",
            "202814",
            "369863",
            "75474",
            "889",
            "1831304",
            "3018",
            "3042",
            "2022",
            "2022-05-24",
            "75.0000",
            "1990.0000",
            "149250.00",
            "1990.0000",
            "149250.00",
            "149250.00"
          ],
          "rowNumber": 1829602,
          "rowPosition": 1829603,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75474\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829603\" violates the foreign key: for \"id_contrato\": values \"75474\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44026",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "60455",
            "1",
            "60",
            "326",
            "983",
            "274253",
            "370106",
            "75471",
            "889",
            "1831952",
            "2742",
            "3043",
            "2022",
            "2022-05-27",
            "100.0000",
            "2439.2700",
            "243927.00",
            "2439.2700",
            "243927.00",
            "243927.00"
          ],
          "rowNumber": 1830884,
          "rowPosition": 1830885,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75471\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830885\" violates the foreign key: for \"id_contrato\": values \"75471\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44004",
            "4",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "17398",
            "1",
            "42",
            "399",
            "10482",
            "266614",
            "370218",
            "75480",
            "1729",
            "1831334",
            "2923",
            "2078",
            "2022",
            "2022-05-31",
            "1.0000",
            "66500.0000",
            "66500.00",
            "48920.0000",
            "48920.00",
            "48920.00"
          ],
          "rowNumber": 1831111,
          "rowPosition": 1831112,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75480\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831112\" violates the foreign key: for \"id_contrato\": values \"75480\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44004",
            "4",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "17398",
            "1",
            "42",
            "399",
            "333",
            "264642",
            "370218",
            "75480",
            "889",
            "1831334",
            "2923",
            "2078",
            "2022",
            "2022-05-31",
            "2.0000",
            "4900.0000",
            "9800.00",
            "5540.0000",
            "11080.00",
            "11080.00"
          ],
          "rowNumber": 1831112,
          "rowPosition": 1831113,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75480\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831113\" violates the foreign key: for \"id_contrato\": values \"75480\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44017",
            "14",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "69194",
            "1",
            "32",
            "100",
            "8178",
            "128864",
            "370227",
            "75477",
            "611",
            "1831400",
            "2796",
            "2082",
            "2022",
            "2022-05-31",
            "2000.0000",
            "0.9600",
            "1910.00",
            "0.8500",
            "1700.00",
            "1700.00"
          ],
          "rowNumber": 1831196,
          "rowPosition": 1831197,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75477\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831197\" violates the foreign key: for \"id_contrato\": values \"75477\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "145098",
            "369185",
            "75483",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "20.0000",
            "419.0000",
            "8380.00",
            "419.0000",
            "8380.00",
            "8380.00"
          ],
          "rowNumber": 1831752,
          "rowPosition": 1831753,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831753\" violates the foreign key: for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "17171",
            "124786",
            "369185",
            "75473",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "1.0000",
            "440.0000",
            "440.00",
            "440.0000",
            "440.00",
            "440.00"
          ],
          "rowNumber": 1831753,
          "rowPosition": 1831754,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831754\" violates the foreign key: for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "4032",
            "156228",
            "369185",
            "75473",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "8.0000",
            "520.0000",
            "4160.00",
            "520.0000",
            "4160.00",
            "4160.00"
          ],
          "rowNumber": 1831755,
          "rowPosition": 1831756,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831756\" violates the foreign key: for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "156231",
            "369185",
            "75483",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "10.0000",
            "519.0000",
            "5190.00",
            "519.0000",
            "5190.00",
            "5190.00"
          ],
          "rowNumber": 1831756,
          "rowPosition": 1831757,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831757\" violates the foreign key: for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6570",
            "204163",
            "369185",
            "75483",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "11.0000",
            "1139.0000",
            "12529.00",
            "1139.0000",
            "12529.00",
            "12529.00"
          ],
          "rowNumber": 1831757,
          "rowPosition": 1831758,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831758\" violates the foreign key: for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "19415",
            "1",
            "54",
            "119",
            "9290",
            "125455",
            "369185",
            "75479",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "1.0000",
            "380.0000",
            "380.00",
            "380.0000",
            "380.00",
            "380.00"
          ],
          "rowNumber": 1831758,
          "rowPosition": 1831759,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75479\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831759\" violates the foreign key: for \"id_contrato\": values \"75479\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "9301",
            "116075",
            "369185",
            "75473",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "1.0000",
            "340.0000",
            "340.00",
            "340.0000",
            "340.00",
            "340.00"
          ],
          "rowNumber": 1831760,
          "rowPosition": 1831761,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831761\" violates the foreign key: for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "14376",
            "155896",
            "369185",
            "75473",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "26.0000",
            "760.0000",
            "19760.00",
            "760.0000",
            "19760.00",
            "19760.00"
          ],
          "rowNumber": 1831761,
          "rowPosition": 1831762,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831762\" violates the foreign key: for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6570",
            "137324",
            "369185",
            "75483",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "2.0000",
            "1479.0000",
            "2958.00",
            "1479.0000",
            "2958.00",
            "2958.00"
          ],
          "rowNumber": 1831763,
          "rowPosition": 1831764,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831764\" violates the foreign key: for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "502",
            "14376",
            "128397",
            "369185",
            "75463",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "12.0000",
            "1676.0900",
            "20113.08",
            "1676.0900",
            "20113.08",
            "20113.08"
          ],
          "rowNumber": 1831764,
          "rowPosition": 1831765,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831765\" violates the foreign key: for \"id_contrato\": values \"75463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "502",
            "15252",
            "138494",
            "369185",
            "75463",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "17.0000",
            "631.3800",
            "10733.46",
            "631.3800",
            "10733.46",
            "10733.46"
          ],
          "rowNumber": 1831765,
          "rowPosition": 1831766,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831766\" violates the foreign key: for \"id_contrato\": values \"75463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "15506",
            "1",
            "54",
            "502",
            "6435",
            "204161",
            "369185",
            "75464",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "21.0000",
            "426.0000",
            "8946.00",
            "426.0000",
            "8946.00",
            "8946.00"
          ],
          "rowNumber": 1831767,
          "rowPosition": 1831768,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831768\" violates the foreign key: for \"id_contrato\": values \"75464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "9",
            "6209",
            "33846",
            "369185",
            "75463",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "3.0000",
            "1921.0000",
            "5763.00",
            "1921.0000",
            "5763.00",
            "5763.00"
          ],
          "rowNumber": 1831768,
          "rowPosition": 1831769,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831769\" violates the foreign key: for \"id_contrato\": values \"75463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "9301",
            "130872",
            "369185",
            "75473",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "1.0000",
            "850.0000",
            "850.00",
            "850.0000",
            "850.00",
            "850.00"
          ],
          "rowNumber": 1831769,
          "rowPosition": 1831770,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831770\" violates the foreign key: for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "776",
            "4035",
            "132250",
            "369185",
            "75473",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "20.0000",
            "132.0000",
            "2640.00",
            "132.0000",
            "2640.00",
            "2640.00"
          ],
          "rowNumber": 1831770,
          "rowPosition": 1831771,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831771\" violates the foreign key: for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "144721",
            "369185",
            "75483",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "66.0000",
            "768.0000",
            "50688.00",
            "768.0000",
            "50688.00",
            "50688.00"
          ],
          "rowNumber": 1831771,
          "rowPosition": 1831772,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831772\" violates the foreign key: for \"id_contrato\": values \"75483\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "17171",
            "136219",
            "369185",
            "75473",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-05-16",
            "16.0000",
            "604.0000",
            "9664.00",
            "604.0000",
            "9664.00",
            "9664.00"
          ],
          "rowNumber": 1831772,
          "rowPosition": 1831773,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831773\" violates the foreign key: for \"id_contrato\": values \"75473\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44018",
            "2",
            "1831105",
            "91",
            "1",
            "1",
            "738",
            "71180",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "370001",
            "75476",
            "322",
            "1831697",
            "2669",
            "3042",
            "2022",
            "2022-05-26",
            "0.0000",
            "399969.0000",
            "399969.00",
            "399969.0000",
            "399969.00",
            "399969.00"
          ],
          "rowNumber": 1833689,
          "rowPosition": 1833690,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75476\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833690\" violates the foreign key: for \"id_contrato\": values \"75476\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "501",
            "61546",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "370464",
            "75470",
            "889",
            "1831500",
            "2670",
            "2082",
            "2022",
            "2022-06-02",
            "0.0000",
            "70720.0000",
            "70720.00",
            "60000.0000",
            "60000.00",
            "60000.00"
          ],
          "rowNumber": 1835369,
          "rowPosition": 1835370,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75470\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835370\" violates the foreign key: for \"id_contrato\": values \"75470\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "19202",
            "1",
            "46",
            "10",
            "316",
            "133065",
            "369300",
            "75467",
            "889",
            "1831846",
            "3078",
            "2046",
            "2022",
            "2022-05-17",
            "1.0000",
            "499.0000",
            "499.00",
            "499.0000",
            "499.00",
            "499.00"
          ],
          "rowNumber": 1835605,
          "rowPosition": 1835606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75467\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835606\" violates the foreign key: for \"id_contrato\": values \"75467\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "30244",
            "1",
            "46",
            "123",
            "5527",
            "59113",
            "370411",
            "75478",
            "889",
            "1831340",
            "3084",
            "2081",
            "2022",
            "2022-06-02",
            "80.0000",
            "277.7500",
            "22220.00",
            "61.2500",
            "4900.00",
            "4900.00"
          ],
          "rowNumber": 1835773,
          "rowPosition": 1835774,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835774\" violates the foreign key: for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "30244",
            "1",
            "43",
            "328",
            "2633",
            "20207",
            "370411",
            "75478",
            "943",
            "1831340",
            "3084",
            "2081",
            "2022",
            "2022-06-02",
            "900.0000",
            "3.4400",
            "3096.00",
            "3.4400",
            "3096.00",
            "3096.00"
          ],
          "rowNumber": 1835774,
          "rowPosition": 1835775,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835775\" violates the foreign key: for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "30244",
            "1",
            "43",
            "328",
            "2633",
            "49547",
            "370411",
            "75478",
            "943",
            "1831340",
            "3084",
            "2081",
            "2022",
            "2022-06-02",
            "2500.0000",
            "4.2900",
            "10725.00",
            "2.9000",
            "7250.00",
            "7250.00"
          ],
          "rowNumber": 1835775,
          "rowPosition": 1835776,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835776\" violates the foreign key: for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "30244",
            "1",
            "63",
            "638",
            "12008",
            "144842",
            "370411",
            "75478",
            "889",
            "1831026",
            "3084",
            "2081",
            "2022",
            "2022-06-02",
            "1200.0000",
            "7.8500",
            "9420.00",
            "7.4100",
            "8892.00",
            "8892.00"
          ],
          "rowNumber": 1836115,
          "rowPosition": 1836116,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1836116\" violates the foreign key: for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "30244",
            "1",
            "46",
            "610",
            "117",
            "145511",
            "370411",
            "75478",
            "830",
            "1831845",
            "3084",
            "2081",
            "2022",
            "2022-06-02",
            "300.0000",
            "74.3100",
            "22293.00",
            "74.3100",
            "22293.00",
            "22293.00"
          ],
          "rowNumber": 1836116,
          "rowPosition": 1836117,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1836117\" violates the foreign key: for \"id_contrato\": values \"75478\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44025",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "24176",
            "1",
            "89",
            "535",
            "2311",
            "167782",
            "370065",
            "75469",
            "889",
            "1831991",
            "2746",
            "3043",
            "2022",
            "2022-05-26",
            "2.0000",
            "2050.0000",
            "4100.00",
            "2050.0000",
            "4100.00",
            "4100.00"
          ],
          "rowNumber": 1836255,
          "rowPosition": 1836256,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75469\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1836256\" violates the foreign key: for \"id_contrato\": values \"75469\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "2",
            "1831037",
            "28",
            "1",
            "1",
            "876",
            "31915",
            "1",
            "39",
            "130",
            "7129",
            "180359",
            "367953",
            "75468",
            "1729",
            "1831812",
            "3065",
            "1861",
            "2022",
            "2022-04-28",
            "0.0000",
            "1795.0000",
            "1795.00",
            "1795.0000",
            "1795.00",
            "1795.00"
          ],
          "rowNumber": 1838411,
          "rowPosition": 1838412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75468\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1838412\" violates the foreign key: for \"id_contrato\": values \"75468\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "2",
            "1831037",
            "28",
            "1",
            "1",
            "876",
            "31915",
            "1",
            "39",
            "299",
            "10248",
            "148706",
            "367953",
            "75468",
            "889",
            "1831812",
            "3065",
            "1861",
            "2022",
            "2022-04-28",
            "0.0000",
            "19968.0000",
            "19968.00",
            "19968.0000",
            "19968.00",
            "19968.00"
          ],
          "rowNumber": 1838412,
          "rowPosition": 1838413,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75468\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1838413\" violates the foreign key: for \"id_contrato\": values \"75468\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "2",
            "1831037",
            "28",
            "1",
            "1",
            "876",
            "31915",
            "1",
            "39",
            "299",
            "10248",
            "138566",
            "367953",
            "75468",
            "889",
            "1831812",
            "3065",
            "1861",
            "2022",
            "2022-04-28",
            "0.0000",
            "10800.0000",
            "10800.00",
            "10800.0000",
            "10800.00",
            "10800.00"
          ],
          "rowNumber": 1838413,
          "rowPosition": 1838414,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75468\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1838414\" violates the foreign key: for \"id_contrato\": values \"75468\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "32672",
            "1",
            "42",
            "399",
            "15242",
            "131732",
            "367963",
            "75481",
            "889",
            "1831334",
            "2923",
            "2082",
            "2022",
            "2022-04-28",
            "22000.0000",
            "165.5000",
            "3641000.00",
            "148.0000",
            "3256000.00",
            "3256000.00"
          ],
          "rowNumber": 1839609,
          "rowPosition": 1839610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75481\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1839610\" violates the foreign key: for \"id_contrato\": values \"75481\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "93794",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "900000.0000",
            "900000.00",
            "12500.0000",
            "12500.00",
            "12500.00"
          ],
          "rowNumber": 1841830,
          "rowPosition": 1841831,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841831\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "153187",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "61500.0000",
            "61500.00",
            "240000.0000",
            "240000.00",
            "240000.00"
          ],
          "rowNumber": 1841831,
          "rowPosition": 1841832,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841832\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "113541",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "256500.0000",
            "256500.00",
            "75000.0000",
            "75000.00",
            "75000.00"
          ],
          "rowNumber": 1841832,
          "rowPosition": 1841833,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841833\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "151468",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "19500.0000",
            "19500.00",
            "33300.0000",
            "33300.00",
            "33300.00"
          ],
          "rowNumber": 1841833,
          "rowPosition": 1841834,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841834\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "151468",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "13050.0000",
            "13050.00",
            "37500.0000",
            "37500.00",
            "37500.00"
          ],
          "rowNumber": 1841834,
          "rowPosition": 1841835,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841835\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "151468",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "54000.0000",
            "54000.00",
            "861000.0000",
            "861000.00",
            "861000.00"
          ],
          "rowNumber": 1841836,
          "rowPosition": 1841837,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841837\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "113541",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "24750.0000",
            "24750.00",
            "3900.0000",
            "3900.00",
            "3900.00"
          ],
          "rowNumber": 1841837,
          "rowPosition": 1841838,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841838\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27013",
            "1",
            "77",
            "271",
            "1817",
            "151123",
            "370548",
            "75466",
            "889",
            "1831744",
            "2937",
            "2633",
            "2022",
            "2022-06-03",
            "0.0000",
            "28500.0000",
            "28500.00",
            "94500.0000",
            "94500.00",
            "94500.00"
          ],
          "rowNumber": 1841838,
          "rowPosition": 1841839,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841839\" violates the foreign key: for \"id_contrato\": values \"75466\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50339",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "883",
            "30248",
            "1",
            "77",
            "533",
            "9643",
            "90741",
            "368996",
            "75475",
            "889",
            "1831749",
            "2594",
            "2082",
            "2022",
            "2022-05-12",
            "0.0000",
            "140181.0000",
            "140181.00",
            "140181.0000",
            "140181.00",
            "140181.00"
          ],
          "rowNumber": 1842957,
          "rowPosition": 1842958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75475\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1842958\" violates the foreign key: for \"id_contrato\": values \"75475\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44033",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "24550",
            "1",
            "56",
            "729",
            "1195",
            "127329",
            "370513",
            "75472",
            "595",
            "1831940",
            "2927",
            "3043",
            "2022",
            "2022-06-03",
            "7.0000",
            "79.0000",
            "553.00",
            "79.0000",
            "553.00",
            "553.00"
          ],
          "rowNumber": 1843622,
          "rowPosition": 1843623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75472\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1843623\" violates the foreign key: for \"id_contrato\": values \"75472\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44033",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "24550",
            "1",
            "56",
            "729",
            "8955",
            "123036",
            "370513",
            "75472",
            "595",
            "1831329",
            "2927",
            "3043",
            "2022",
            "2022-06-03",
            "7.0000",
            "118.5000",
            "829.50",
            "118.5000",
            "829.50",
            "829.50"
          ],
          "rowNumber": 1843624,
          "rowPosition": 1843625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75472\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1843625\" violates the foreign key: for \"id_contrato\": values \"75472\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 58
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 58,
    "tasks": 1
  },
  "valid": false
}