{
  "version": "4.22.3",
  "time": 0.938,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_convenio_entrada",
        "title": "Convênio Entrada - tabela fato",
        "path": "data/ft_convenio_entrada.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao",
              "title": "Órgão - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_convenio",
              "title": "Convênio de Entrada - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_concedente",
              "title": "Concedente - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao",
              "title": "Situação do Convênio - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "vr_concedente_atual",
              "title": "Valor Concedente Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ",",
              "description": "Valor financeiro previsto no convênio para o concedente repassar ao proponente, incluindo termos aditivos.\n",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_proponente_atual",
              "title": "Valor Proponente Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ",",
              "description": "Valor previsto no convênio para o proponente dar como contrapartida financeira, incluindo termos aditivos.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_orgao"
              ],
              "reference": {
                "fields": [
                  "id_orgao"
                ],
                "resource": "dm_orgao_proponente"
              }
            },
            {
              "fields": [
                "id_situacao"
              ],
              "reference": {
                "fields": [
                  "id_situacao"
                ],
                "resource": "dm_situacao_conv_ent"
              }
            },
            {
              "fields": [
                "id_concedente"
              ],
              "reference": {
                "fields": [
                  "id_concedente"
                ],
                "resource": "dm_concedente"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_convenio"
              ],
              "reference": {
                "fields": [
                  "id_convenio"
                ],
                "resource": "dm_convenio_entrada"
              }
            },
            {
              "fields": [
                "id_unidade_orc"
              ],
              "reference": {
                "fields": [
                  "id_unidade_orc"
                ],
                "resource": "dm_unidade_orc"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_convenio_entrada"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "d62b638e27e5f01146fdaeafb0dabe44",
          "bytes": 25948,
          "fields": 9,
          "rows": 1714
        }
      },
      "time": 0.938,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "50295",
            "57",
            "1733",
            "857",
            "4159",
            "1",
            "2021",
            "7975230.35",
            "0.00"
          ],
          "rowNumber": 310,
          "rowPosition": 311,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"311\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50294",
            "57",
            "1734",
            "377",
            "4159",
            "1",
            "2021",
            "200000.00",
            "4000.00"
          ],
          "rowNumber": 317,
          "rowPosition": 318,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"318\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50274",
            "57",
            "1729",
            "1234",
            "4159",
            "1",
            "2021",
            "8726.87",
            "1745.37"
          ],
          "rowNumber": 320,
          "rowPosition": 321,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"321\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50274",
            "57",
            "1729",
            "1234",
            "4159",
            "1",
            "2021",
            "8726.87",
            "1745.37"
          ],
          "rowNumber": 320,
          "rowPosition": 321,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"321\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49901",
            "57",
            "1727",
            "1209",
            "4159",
            "1",
            "2021",
            "2153454.81",
            "47525.58"
          ],
          "rowNumber": 335,
          "rowPosition": 336,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"336\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50283",
            "57",
            "1731",
            "328",
            "4159",
            "1",
            "2021",
            "10000.00",
            "2000.00"
          ],
          "rowNumber": 337,
          "rowPosition": 338,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"338\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50274",
            "57",
            "1728",
            "515",
            "4159",
            "1",
            "2021",
            "15673.18",
            "3134.64"
          ],
          "rowNumber": 339,
          "rowPosition": 340,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"340\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50274",
            "57",
            "1726",
            "158",
            "4159",
            "1",
            "2021",
            "15673.18",
            "3134.64"
          ],
          "rowNumber": 342,
          "rowPosition": 343,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"343\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50269",
            "57",
            "1723",
            "15",
            "4159",
            "1",
            "2021",
            "150000.00",
            "30000.00"
          ],
          "rowNumber": 344,
          "rowPosition": 345,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"345\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50283",
            "40",
            "1732",
            "103",
            "4089",
            "1",
            "2021",
            "763013.13",
            "0.00"
          ],
          "rowNumber": 548,
          "rowPosition": 549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"549\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50262",
            "40",
            "1730",
            "103",
            "4089",
            "1",
            "2021",
            "960000.00",
            "0.00"
          ],
          "rowNumber": 549,
          "rowPosition": 550,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"550\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49920",
            "16",
            "1725",
            "416",
            "4165",
            "1",
            "2021",
            "250000.00",
            "40449.33"
          ],
          "rowNumber": 586,
          "rowPosition": 587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"587\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49920",
            "16",
            "1724",
            "416",
            "4165",
            "1",
            "2021",
            "10000000.00",
            "265534.00"
          ],
          "rowNumber": 587,
          "rowPosition": 588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"588\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50300",
            "35",
            "1736",
            "1209",
            "4174",
            "1",
            "2021",
            "19996677.30",
            "415749.75"
          ],
          "rowNumber": 604,
          "rowPosition": 605,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"605\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50300",
            "35",
            "1735",
            "1209",
            "4174",
            "1",
            "2021",
            "21998833.92",
            "467414.08"
          ],
          "rowNumber": 605,
          "rowPosition": 606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"606\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 15
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 15,
    "tasks": 1
  },
  "valid": false
}