{
  "version": "4.28.0",
  "time": 218.065,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "69a6e20143d6aa170f49251da2c95d0a",
          "bytes": 55899240,
          "fields": 27,
          "rows": 1828329
        }
      },
      "time": 218.065,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43962",
            "14",
            "1831094",
            "95",
            "1",
            "1",
            "790",
            "28359",
            "1",
            "69",
            "439",
            "21705",
            "174016",
            "366418",
            "74685",
            "1927",
            "1831312",
            "2538",
            "3043",
            "2022",
            "2022-04-01",
            "1200.0000",
            "10.6200",
            "12747.00",
            "9.7000",
            "11640.00",
            "11640.00"
          ],
          "rowNumber": 1800138,
          "rowPosition": 1800139,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74685\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800139\" violates the foreign key: for \"id_contrato\": values \"74685\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "12146",
            "144042",
            "366360",
            "74684",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-04-01",
            "180.0000",
            "272.9700",
            "49134.60",
            "272.9700",
            "49134.60",
            "49134.60"
          ],
          "rowNumber": 1801433,
          "rowPosition": 1801434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801434\" violates the foreign key: for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "20473",
            "112582",
            "366360",
            "74684",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-04-01",
            "462.0000",
            "377.4700",
            "174391.14",
            "377.4700",
            "174391.14",
            "174391.14"
          ],
          "rowNumber": 1801434,
          "rowPosition": 1801435,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801435\" violates the foreign key: for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "13232",
            "148162",
            "366360",
            "74684",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-04-01",
            "2273.0000",
            "32.2600",
            "73326.98",
            "32.2600",
            "73326.98",
            "73326.98"
          ],
          "rowNumber": 1801435,
          "rowPosition": 1801436,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801436\" violates the foreign key: for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "20473",
            "138813",
            "366360",
            "74684",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-04-01",
            "446.0000",
            "337.0400",
            "150319.84",
            "337.0400",
            "150319.84",
            "150319.84"
          ],
          "rowNumber": 1801436,
          "rowPosition": 1801437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801437\" violates the foreign key: for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "12146",
            "137476",
            "366360",
            "74684",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-04-01",
            "495.0000",
            "299.8300",
            "148415.85",
            "299.8300",
            "148415.85",
            "148415.85"
          ],
          "rowNumber": 1801437,
          "rowPosition": 1801438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801438\" violates the foreign key: for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "13232",
            "139833",
            "366360",
            "74684",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-04-01",
            "2273.0000",
            "32.2600",
            "73326.98",
            "32.2600",
            "73326.98",
            "73326.98"
          ],
          "rowNumber": 1801438,
          "rowPosition": 1801439,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801439\" violates the foreign key: for \"id_contrato\": values \"74684\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "2018",
            "130544",
            "366374",
            "74669",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-04-01",
            "190.0000",
            "142.6500",
            "27103.50",
            "142.6500",
            "27103.50",
            "27103.50"
          ],
          "rowNumber": 1801440,
          "rowPosition": 1801441,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74669\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801441\" violates the foreign key: for \"id_contrato\": values \"74669\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50338",
            "4",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "21005",
            "1",
            "39",
            "283",
            "21770",
            "193662",
            "365341",
            "74681",
            "889",
            "1831736",
            "3067",
            "2839",
            "2022",
            "2022-03-15",
            "0.0000",
            "61635.0000",
            "61635.00",
            "59999.1000",
            "59999.10",
            "59999.10"
          ],
          "rowNumber": 1802798,
          "rowPosition": 1802799,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74681\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802799\" violates the foreign key: for \"id_contrato\": values \"74681\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "21260",
            "1",
            "32",
            "100",
            "8792",
            "28009",
            "366058",
            "74680",
            "889",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-03-28",
            "84.0000",
            "233.3100",
            "19598.04",
            "233.3100",
            "19598.04",
            "19598.04"
          ],
          "rowNumber": 1804828,
          "rowPosition": 1804829,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74680\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804829\" violates the foreign key: for \"id_contrato\": values \"74680\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "18920",
            "1",
            "32",
            "100",
            "2946",
            "40318",
            "366058",
            "74682",
            "969",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-03-28",
            "10.0000",
            "1380.0000",
            "13800.00",
            "793.6000",
            "7936.00",
            "7936.00"
          ],
          "rowNumber": 1804829,
          "rowPosition": 1804830,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804830\" violates the foreign key: for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "18920",
            "1",
            "32",
            "100",
            "2946",
            "146589",
            "366058",
            "74682",
            "1872",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-03-28",
            "10.0000",
            "740.0000",
            "7400.00",
            "359.6800",
            "3596.80",
            "3596.80"
          ],
          "rowNumber": 1804830,
          "rowPosition": 1804831,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804831\" violates the foreign key: for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "18920",
            "1",
            "32",
            "100",
            "2946",
            "64079",
            "366058",
            "74682",
            "613",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-03-28",
            "16.0000",
            "1450.0000",
            "23200.00",
            "800.0000",
            "12800.00",
            "12800.00"
          ],
          "rowNumber": 1804831,
          "rowPosition": 1804832,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804832\" violates the foreign key: for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "18920",
            "1",
            "32",
            "100",
            "2946",
            "64080",
            "366058",
            "74682",
            "637",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-03-28",
            "2.0000",
            "2300.0000",
            "4600.00",
            "1400.0000",
            "2800.00",
            "2800.00"
          ],
          "rowNumber": 1804832,
          "rowPosition": 1804833,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804833\" violates the foreign key: for \"id_contrato\": values \"74682\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "100",
            "2946",
            "143908",
            "366058",
            "74672",
            "613",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-03-28",
            "10.0000",
            "860.0000",
            "8600.00",
            "600.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1804833,
          "rowPosition": 1804834,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74672\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804834\" violates the foreign key: for \"id_contrato\": values \"74672\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "100",
            "2946",
            "40317",
            "366058",
            "74672",
            "656",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-03-28",
            "4.0000",
            "890.0000",
            "3560.00",
            "650.0000",
            "2600.00",
            "2600.00"
          ],
          "rowNumber": 1804835,
          "rowPosition": 1804836,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74672\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804836\" violates the foreign key: for \"id_contrato\": values \"74672\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49906",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "100",
            "2946",
            "70862",
            "366089",
            "74672",
            "656",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-03-28",
            "5.0000",
            "890.0000",
            "4450.00",
            "720.0000",
            "3600.00",
            "3600.00"
          ],
          "rowNumber": 1805364,
          "rowPosition": 1805365,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74672\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805365\" violates the foreign key: for \"id_contrato\": values \"74672\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "4032",
            "315154",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "830.0000",
            "830.00",
            "705.0000",
            "705.00",
            "705.00"
          ],
          "rowNumber": 1806973,
          "rowPosition": 1806974,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806974\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "9",
            "11970",
            "196979",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "435.0000",
            "870.00",
            "370.0000",
            "740.00",
            "740.00"
          ],
          "rowNumber": 1806974,
          "rowPosition": 1806975,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806975\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "14376",
            "155894",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "1160.0000",
            "2320.00",
            "963.0000",
            "1926.00",
            "1926.00"
          ],
          "rowNumber": 1806975,
          "rowPosition": 1806976,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806976\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "14376",
            "163369",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "680.0000",
            "680.00",
            "562.0000",
            "562.00",
            "562.00"
          ],
          "rowNumber": 1806976,
          "rowPosition": 1806977,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806977\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "14376",
            "184156",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "1240.0000",
            "1240.00",
            "1032.0000",
            "1032.00",
            "1032.00"
          ],
          "rowNumber": 1806977,
          "rowPosition": 1806978,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806978\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "4032",
            "151143",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "880.0000",
            "880.00",
            "738.0000",
            "738.00",
            "738.00"
          ],
          "rowNumber": 1806978,
          "rowPosition": 1806979,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806979\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "14497",
            "154325",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "705.0000",
            "705.00",
            "583.0000",
            "583.00",
            "583.00"
          ],
          "rowNumber": 1806979,
          "rowPosition": 1806980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806980\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "17171",
            "166764",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "2450.0000",
            "2450.00",
            "2053.0000",
            "2053.00",
            "2053.00"
          ],
          "rowNumber": 1807680,
          "rowPosition": 1807681,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807681\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "17171",
            "153018",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "7662.0000",
            "15324.00",
            "6584.0000",
            "13168.00",
            "13168.00"
          ],
          "rowNumber": 1807681,
          "rowPosition": 1807682,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807682\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "17171",
            "145165",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "6960.0000",
            "13920.00",
            "5975.0000",
            "11950.00",
            "11950.00"
          ],
          "rowNumber": 1807682,
          "rowPosition": 1807683,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807683\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "9",
            "6609",
            "138837",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "2290.0000",
            "2290.00",
            "1893.0000",
            "1893.00",
            "1893.00"
          ],
          "rowNumber": 1807683,
          "rowPosition": 1807684,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807684\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "9301",
            "135664",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "6.0000",
            "610.0000",
            "3660.00",
            "517.0000",
            "3102.00",
            "3102.00"
          ],
          "rowNumber": 1807684,
          "rowPosition": 1807685,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807685\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "6435",
            "133593",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "30.0000",
            "639.0000",
            "19170.00",
            "526.0000",
            "15780.00",
            "15780.00"
          ],
          "rowNumber": 1807685,
          "rowPosition": 1807686,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807686\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "6435",
            "153780",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "45.0000",
            "1592.0000",
            "71640.00",
            "1222.0000",
            "54990.00",
            "54990.00"
          ],
          "rowNumber": 1807686,
          "rowPosition": 1807687,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807687\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "6435",
            "154754",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "12.0000",
            "1230.0000",
            "14760.00",
            "1033.0000",
            "12396.00",
            "12396.00"
          ],
          "rowNumber": 1807687,
          "rowPosition": 1807688,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807688\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "9",
            "6568",
            "167262",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "66.0000",
            "430.0000",
            "28380.00",
            "364.0000",
            "24024.00",
            "24024.00"
          ],
          "rowNumber": 1807688,
          "rowPosition": 1807689,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807689\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "9",
            "6568",
            "173255",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "8.0000",
            "318.0000",
            "2544.00",
            "267.0000",
            "2136.00",
            "2136.00"
          ],
          "rowNumber": 1807689,
          "rowPosition": 1807690,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807690\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "6435",
            "151676",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "3659.5000",
            "3659.50",
            "3102.0000",
            "3102.00",
            "3102.00"
          ],
          "rowNumber": 1807690,
          "rowPosition": 1807691,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807691\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "6435",
            "171455",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "5830.0000",
            "5830.00",
            "4898.0000",
            "4898.00",
            "4898.00"
          ],
          "rowNumber": 1807691,
          "rowPosition": 1807692,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807692\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "6435",
            "171444",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "1633.0000",
            "3266.00",
            "1331.0000",
            "2662.00",
            "2662.00"
          ],
          "rowNumber": 1807692,
          "rowPosition": 1807693,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807693\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "6435",
            "126103",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "3976.0000",
            "7952.00",
            "3409.0000",
            "6818.00",
            "6818.00"
          ],
          "rowNumber": 1807693,
          "rowPosition": 1807694,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807694\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "19883",
            "165385",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "3640.0000",
            "7280.00",
            "3073.0000",
            "6146.00",
            "6146.00"
          ],
          "rowNumber": 1807694,
          "rowPosition": 1807695,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807695\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "14376",
            "128397",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "4.0000",
            "2125.0000",
            "8500.00",
            "1762.0000",
            "7048.00",
            "7048.00"
          ],
          "rowNumber": 1807695,
          "rowPosition": 1807696,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807696\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "66530",
            "1",
            "54",
            "119",
            "17031",
            "339057",
            "366775",
            "74675",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "57.0000",
            "3054.8400",
            "174125.88",
            "3003.0000",
            "171171.00",
            "171171.00"
          ],
          "rowNumber": 1807696,
          "rowPosition": 1807697,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807697\" violates the foreign key: for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "66530",
            "1",
            "54",
            "119",
            "17031",
            "339046",
            "366775",
            "74675",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "2272.3800",
            "4544.76",
            "2210.5600",
            "4421.12",
            "4421.12"
          ],
          "rowNumber": 1807697,
          "rowPosition": 1807698,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807698\" violates the foreign key: for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "66530",
            "1",
            "54",
            "119",
            "17031",
            "339058",
            "366775",
            "74675",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "11.0000",
            "1484.8800",
            "16333.68",
            "1390.9100",
            "15300.01",
            "15300.01"
          ],
          "rowNumber": 1807698,
          "rowPosition": 1807699,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807699\" violates the foreign key: for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "66530",
            "1",
            "54",
            "502",
            "14376",
            "339056",
            "366775",
            "74675",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "2661.7200",
            "2661.72",
            "2939.9700",
            "2939.97",
            "2939.97"
          ],
          "rowNumber": 1807699,
          "rowPosition": 1807700,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807700\" violates the foreign key: for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "66530",
            "1",
            "54",
            "9",
            "10761",
            "340047",
            "366775",
            "74675",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "2403.4200",
            "2403.42",
            "2671.2000",
            "2671.20",
            "2671.20"
          ],
          "rowNumber": 1807700,
          "rowPosition": 1807701,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807701\" violates the foreign key: for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "66530",
            "1",
            "54",
            "119",
            "15267",
            "339048",
            "366775",
            "74675",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "1.0000",
            "3354.7200",
            "3354.72",
            "3563.0000",
            "3563.00",
            "3563.00"
          ],
          "rowNumber": 1807701,
          "rowPosition": 1807702,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807702\" violates the foreign key: for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "66530",
            "1",
            "54",
            "9",
            "11936",
            "339250",
            "366775",
            "74675",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "10.0000",
            "1276.3800",
            "12763.80",
            "971.3700",
            "9713.70",
            "9713.70"
          ],
          "rowNumber": 1807702,
          "rowPosition": 1807703,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807703\" violates the foreign key: for \"id_contrato\": values \"74675\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "14376",
            "160606",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "10.0000",
            "1910.0000",
            "19100.00",
            "1619.0000",
            "16190.00",
            "16190.00"
          ],
          "rowNumber": 1807703,
          "rowPosition": 1807704,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807704\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "14376",
            "153622",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "13.0000",
            "979.0000",
            "12727.00",
            "838.0000",
            "10894.00",
            "10894.00"
          ],
          "rowNumber": 1807704,
          "rowPosition": 1807705,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807705\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "4062",
            "134013",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "2340.0000",
            "4680.00",
            "1985.0000",
            "3970.00",
            "3970.00"
          ],
          "rowNumber": 1807705,
          "rowPosition": 1807706,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807706\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "17171",
            "315161",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "4.0000",
            "2220.0000",
            "8880.00",
            "1885.0000",
            "7540.00",
            "7540.00"
          ],
          "rowNumber": 1807706,
          "rowPosition": 1807707,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807707\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "17171",
            "139167",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "4.0000",
            "1878.0000",
            "7512.00",
            "1597.0000",
            "6388.00",
            "6388.00"
          ],
          "rowNumber": 1807707,
          "rowPosition": 1807708,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807708\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "4032",
            "196869",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "2.0000",
            "654.0000",
            "1308.00",
            "539.0000",
            "1078.00",
            "1078.00"
          ],
          "rowNumber": 1807708,
          "rowPosition": 1807709,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807709\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "70743",
            "1",
            "54",
            "502",
            "4032",
            "315169",
            "366775",
            "74670",
            "889",
            "1831296",
            "2944",
            "3043",
            "2022",
            "2022-04-07",
            "9.0000",
            "979.0000",
            "8811.00",
            "832.0000",
            "7488.00",
            "7488.00"
          ],
          "rowNumber": 1807709,
          "rowPosition": 1807710,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807710\" violates the foreign key: for \"id_contrato\": values \"74670\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "14",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "24308",
            "1",
            "39",
            "834",
            "21813",
            "206336",
            "366837",
            "74667",
            "889",
            "1831739",
            "3067",
            "3108",
            "2022",
            "2022-04-07",
            "0.0000",
            "12297.0000",
            "12297.00",
            "12296.0000",
            "12296.00",
            "12296.00"
          ],
          "rowNumber": 1807727,
          "rowPosition": 1807728,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74667\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807728\" violates the foreign key: for \"id_contrato\": values \"74667\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "883",
            "29765",
            "1",
            "3",
            "627",
            "19215",
            "275597",
            "365066",
            "74673",
            "889",
            "1831295",
            "2611",
            "2046",
            "2022",
            "2022-03-10",
            "5.0000",
            "4693.4800",
            "23467.40",
            "4693.4800",
            "23467.40",
            "23467.40"
          ],
          "rowNumber": 1808243,
          "rowPosition": 1808244,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74673\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1808244\" violates the foreign key: for \"id_contrato\": values \"74673\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50295",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "39065",
            "1",
            "89",
            "664",
            "352",
            "317727",
            "365962",
            "74666",
            "889",
            "1831991",
            "2743",
            "1760",
            "2021",
            "2022-03-29",
            "60.0000",
            "1500.0000",
            "90000.00",
            "1500.0000",
            "90000.00",
            "90000.00"
          ],
          "rowNumber": 1811113,
          "rowPosition": 1811114,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811114\" violates the foreign key: for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50295",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "39065",
            "1",
            "89",
            "664",
            "9674",
            "317529",
            "365962",
            "74666",
            "889",
            "1831991",
            "2743",
            "1760",
            "2021",
            "2022-03-29",
            "5.0000",
            "14827.7700",
            "74138.85",
            "14827.7700",
            "74138.85",
            "74138.85"
          ],
          "rowNumber": 1811114,
          "rowPosition": 1811115,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811115\" violates the foreign key: for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50295",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "39065",
            "1",
            "89",
            "664",
            "9674",
            "317525",
            "365962",
            "74666",
            "889",
            "1831991",
            "2743",
            "1760",
            "2021",
            "2022-03-29",
            "1.0000",
            "7800.0000",
            "7800.00",
            "7800.0000",
            "7800.00",
            "7800.00"
          ],
          "rowNumber": 1811115,
          "rowPosition": 1811116,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811116\" violates the foreign key: for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50295",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "39065",
            "1",
            "89",
            "664",
            "9674",
            "317520",
            "365962",
            "74666",
            "889",
            "1831991",
            "2743",
            "1760",
            "2021",
            "2022-03-29",
            "1.0000",
            "12000.0000",
            "12000.00",
            "12000.0000",
            "12000.00",
            "12000.00"
          ],
          "rowNumber": 1811116,
          "rowPosition": 1811117,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811117\" violates the foreign key: for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50295",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "39065",
            "1",
            "51",
            "276",
            "12334",
            "92308",
            "365962",
            "74666",
            "889",
            "1831625",
            "2670",
            "1760",
            "2021",
            "2022-03-29",
            "0.0000",
            "260248.7100",
            "260248.71",
            "259061.1500",
            "259061.15",
            "259061.15"
          ],
          "rowNumber": 1811117,
          "rowPosition": 1811118,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811118\" violates the foreign key: for \"id_contrato\": values \"74666\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "11643",
            "36346",
            "366495",
            "74676",
            "889",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "1400.0000",
            "4.5000",
            "6300.00",
            "4.5000",
            "6300.00",
            "6300.00"
          ],
          "rowNumber": 1812768,
          "rowPosition": 1812769,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812769\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "16019",
            "29331",
            "366495",
            "74686",
            "62",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "525.0000",
            "28.9500",
            "15198.75",
            "24.6500",
            "12941.25",
            "12941.25"
          ],
          "rowNumber": 1812769,
          "rowPosition": 1812770,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812770\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "16019",
            "29332",
            "366495",
            "74686",
            "62",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "402.0000",
            "29.4500",
            "11838.90",
            "24.6500",
            "9909.30",
            "9909.30"
          ],
          "rowNumber": 1812770,
          "rowPosition": 1812771,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812771\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "16019",
            "211541",
            "366495",
            "74686",
            "1174",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "13.0000",
            "909.65",
            "10.0800",
            "705.60",
            "705.60"
          ],
          "rowNumber": 1812771,
          "rowPosition": 1812772,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812772\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "16019",
            "18810",
            "366495",
            "74686",
            "1174",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "10.5000",
            "734.65",
            "8.9000",
            "623.00",
            "623.00"
          ],
          "rowNumber": 1812772,
          "rowPosition": 1812773,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812773\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "14025",
            "146493",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "490.0000",
            "28.5000",
            "13965.00",
            "16.1200",
            "7898.80",
            "7898.80"
          ],
          "rowNumber": 1812773,
          "rowPosition": 1812774,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812774\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "216",
            "15",
            "66084",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "58.9500",
            "4126.50",
            "27.3000",
            "1911.00",
            "1911.00"
          ],
          "rowNumber": 1812774,
          "rowPosition": 1812775,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812775\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "216",
            "15",
            "59017",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "105.0000",
            "53.9500",
            "5664.75",
            "26.3000",
            "2761.50",
            "2761.50"
          ],
          "rowNumber": 1812775,
          "rowPosition": 1812776,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812776\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "216",
            "15",
            "210586",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "105.0000",
            "51.9500",
            "5454.75",
            "26.3000",
            "2761.50",
            "2761.50"
          ],
          "rowNumber": 1812776,
          "rowPosition": 1812777,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812777\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "216",
            "15",
            "210604",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "105.0000",
            "53.9500",
            "5664.75",
            "26.3000",
            "2761.50",
            "2761.50"
          ],
          "rowNumber": 1812777,
          "rowPosition": 1812778,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812778\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "216",
            "15",
            "210776",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "105.0000",
            "53.9500",
            "5664.75",
            "26.3000",
            "2761.50",
            "2761.50"
          ],
          "rowNumber": 1812778,
          "rowPosition": 1812779,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812779\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "216",
            "15",
            "210585",
            "366495",
            "74686",
            "889",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "840.0000",
            "4.4000",
            "3691.80",
            "3.2000",
            "2688.00",
            "2688.00"
          ],
          "rowNumber": 1812779,
          "rowPosition": 1812780,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812780\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "17143",
            "50249",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "105.0000",
            "33.0000",
            "3465.00",
            "23.8800",
            "2507.40",
            "2507.40"
          ],
          "rowNumber": 1812780,
          "rowPosition": 1812781,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812781\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "14020",
            "28490",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "105.0000",
            "34.9500",
            "3669.75",
            "25.0000",
            "2625.00",
            "2625.00"
          ],
          "rowNumber": 1812781,
          "rowPosition": 1812782,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812782\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "342",
            "14020",
            "210761",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "50.0000",
            "34.9500",
            "1747.50",
            "25.0000",
            "1250.00",
            "1250.00"
          ],
          "rowNumber": 1812782,
          "rowPosition": 1812783,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812783\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "416",
            "2680",
            "26121",
            "366495",
            "74686",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "41.0000",
            "2870.00",
            "35.8800",
            "2511.60",
            "2511.60"
          ],
          "rowNumber": 1812783,
          "rowPosition": 1812784,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812784\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "56215",
            "1",
            "69",
            "507",
            "5927",
            "34612",
            "366495",
            "74686",
            "62",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "54.4500",
            "3811.50",
            "46.9000",
            "3283.00",
            "3283.00"
          ],
          "rowNumber": 1812784,
          "rowPosition": 1812785,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812785\" violates the foreign key: for \"id_contrato\": values \"74686\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "446",
            "21581",
            "170046",
            "366495",
            "74676",
            "1544",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "210.0000",
            "21.3600",
            "4485.60",
            "21.3600",
            "4485.60",
            "4485.60"
          ],
          "rowNumber": 1812785,
          "rowPosition": 1812786,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812786\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "740",
            "13114",
            "118998",
            "366495",
            "74676",
            "1174",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "1400.0000",
            "22.0000",
            "30800.00",
            "22.0000",
            "30800.00",
            "30800.00"
          ],
          "rowNumber": 1812786,
          "rowPosition": 1812787,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812787\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "446",
            "11105",
            "157959",
            "366495",
            "74676",
            "453",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "85.0000",
            "15.5000",
            "1317.50",
            "15.5000",
            "1317.50",
            "1317.50"
          ],
          "rowNumber": 1812787,
          "rowPosition": 1812788,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812788\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "740",
            "13114",
            "133463",
            "366495",
            "74676",
            "98",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "6.0000",
            "70.0000",
            "420.00",
            "70.0000",
            "420.00",
            "420.00"
          ],
          "rowNumber": 1812788,
          "rowPosition": 1812789,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812789\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "740",
            "1318",
            "74455",
            "366495",
            "74676",
            "1181",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "280.0000",
            "17.0000",
            "4760.00",
            "17.0000",
            "4760.00",
            "4760.00"
          ],
          "rowNumber": 1812789,
          "rowPosition": 1812790,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812790\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "507",
            "21582",
            "169930",
            "366495",
            "74676",
            "1883",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "335.0000",
            "4.9900",
            "1671.65",
            "4.9900",
            "1671.65",
            "1671.65"
          ],
          "rowNumber": 1812790,
          "rowPosition": 1812791,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812791\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "507",
            "18981",
            "13173",
            "366495",
            "74676",
            "1307",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "255.0000",
            "26.0000",
            "6630.00",
            "26.0000",
            "6630.00",
            "6630.00"
          ],
          "rowNumber": 1812791,
          "rowPosition": 1812792,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812792\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "507",
            "5927",
            "145659",
            "366495",
            "74676",
            "62",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "35.0000",
            "41.0000",
            "1435.00",
            "41.0000",
            "1435.00",
            "1435.00"
          ],
          "rowNumber": 1812792,
          "rowPosition": 1812793,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812793\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "507",
            "13085",
            "62425",
            "366495",
            "74676",
            "1699",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "35.0000",
            "13.5000",
            "472.50",
            "13.5000",
            "472.50",
            "472.50"
          ],
          "rowNumber": 1812793,
          "rowPosition": 1812794,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812794\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "247",
            "5450",
            "163472",
            "366495",
            "74676",
            "1742",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "352.0000",
            "4.2500",
            "1494.24",
            "4.2400",
            "1492.48",
            "1492.48"
          ],
          "rowNumber": 1812794,
          "rowPosition": 1812795,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812795\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "247",
            "384",
            "126074",
            "366495",
            "74676",
            "191",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "12.0000",
            "840.00",
            "12.0000",
            "840.00",
            "840.00"
          ],
          "rowNumber": 1812795,
          "rowPosition": 1812796,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812796\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "247",
            "384",
            "11523",
            "366495",
            "74676",
            "191",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "10.0000",
            "700.00",
            "10.0000",
            "700.00",
            "700.00"
          ],
          "rowNumber": 1812796,
          "rowPosition": 1812797,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812797\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "247",
            "384",
            "11522",
            "366495",
            "74676",
            "191",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "10.0000",
            "700.00",
            "10.0000",
            "700.00",
            "700.00"
          ],
          "rowNumber": 1812797,
          "rowPosition": 1812798,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812798\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "247",
            "384",
            "15449",
            "366495",
            "74676",
            "191",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "10.0000",
            "700.00",
            "10.0000",
            "700.00",
            "700.00"
          ],
          "rowNumber": 1813619,
          "rowPosition": 1813620,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813620\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "128755",
            "366495",
            "74676",
            "194",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "40.0000",
            "9.0000",
            "360.00",
            "9.0000",
            "360.00",
            "360.00"
          ],
          "rowNumber": 1813620,
          "rowPosition": 1813621,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813621\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "29348",
            "366495",
            "74676",
            "194",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "40.0000",
            "9.0000",
            "360.00",
            "9.0000",
            "360.00",
            "360.00"
          ],
          "rowNumber": 1813621,
          "rowPosition": 1813622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813622\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "126334",
            "366495",
            "74676",
            "194",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "40.0000",
            "9.0000",
            "360.00",
            "9.0000",
            "360.00",
            "360.00"
          ],
          "rowNumber": 1813622,
          "rowPosition": 1813623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813623\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "29350",
            "366495",
            "74676",
            "194",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "40.0000",
            "9.0000",
            "360.00",
            "9.0000",
            "360.00",
            "360.00"
          ],
          "rowNumber": 1813623,
          "rowPosition": 1813624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813624\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "128755",
            "366495",
            "74676",
            "553",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "5.0000",
            "350.00",
            "5.0000",
            "350.00",
            "350.00"
          ],
          "rowNumber": 1813624,
          "rowPosition": 1813625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813625\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "29348",
            "366495",
            "74676",
            "553",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "35.0000",
            "4.5000",
            "157.50",
            "4.5000",
            "157.50",
            "157.50"
          ],
          "rowNumber": 1813625,
          "rowPosition": 1813626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813626\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "126334",
            "366495",
            "74676",
            "553",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "125.0000",
            "4.2500",
            "531.25",
            "4.2500",
            "531.25",
            "531.25"
          ],
          "rowNumber": 1813626,
          "rowPosition": 1813627,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813627\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "439",
            "16669",
            "29350",
            "366495",
            "74676",
            "553",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "4.2500",
            "297.50",
            "4.2500",
            "297.50",
            "297.50"
          ],
          "rowNumber": 1813627,
          "rowPosition": 1813628,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813628\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "740",
            "2862",
            "15411",
            "366495",
            "74676",
            "933",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "10.7500",
            "752.50",
            "10.7500",
            "752.50",
            "752.50"
          ],
          "rowNumber": 1813628,
          "rowPosition": 1813629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813629\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50367",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "16363",
            "1",
            "69",
            "740",
            "2862",
            "120438",
            "366495",
            "74676",
            "933",
            "1831312",
            "2538",
            "2840",
            "2022",
            "2022-04-04",
            "70.0000",
            "11.0000",
            "770.00",
            "11.0000",
            "770.00",
            "770.00"
          ],
          "rowNumber": 1813629,
          "rowPosition": 1813630,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813630\" violates the foreign key: for \"id_contrato\": values \"74676\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48962",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "13711",
            "1",
            "42",
            "399",
            "13649",
            "36728",
            "366573",
            "74671",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-04-04",
            "18000.0000",
            "19.0000",
            "342000.00",
            "5.0300",
            "90540.00",
            "90540.00"
          ],
          "rowNumber": 1814490,
          "rowPosition": 1814491,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74671\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814491\" violates the foreign key: for \"id_contrato\": values \"74671\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "60455",
            "1",
            "60",
            "326",
            "983",
            "274253",
            "366178",
            "74674",
            "889",
            "1831952",
            "2742",
            "3043",
            "2022",
            "2022-03-29",
            "1300.0000",
            "2439.2700",
            "3171051.00",
            "2439.2700",
            "3171051.00",
            "3171051.00"
          ],
          "rowNumber": 1814670,
          "rowPosition": 1814671,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74674\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814671\" violates the foreign key: for \"id_contrato\": values \"74674\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49815",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "66530",
            "1",
            "58",
            "761",
            "21311",
            "151230",
            "365788",
            "74668",
            "889",
            "1831380",
            "2796",
            "3331",
            "2021",
            "2022-03-22",
            "2.0000",
            "7580.2000",
            "15160.40",
            "7575.0000",
            "15150.00",
            "15150.00"
          ],
          "rowNumber": 1817739,
          "rowPosition": 1817740,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74668\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817740\" violates the foreign key: for \"id_contrato\": values \"74668\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49815",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "66530",
            "1",
            "58",
            "761",
            "21311",
            "153009",
            "365788",
            "74668",
            "889",
            "1831380",
            "2796",
            "3331",
            "2021",
            "2022-03-22",
            "6.0000",
            "4047.9800",
            "24287.88",
            "3903.0000",
            "23418.00",
            "23418.00"
          ],
          "rowNumber": 1817740,
          "rowPosition": 1817741,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74668\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817741\" violates the foreign key: for \"id_contrato\": values \"74668\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49815",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "19591",
            "1",
            "58",
            "761",
            "21311",
            "152720",
            "365788",
            "74679",
            "889",
            "1831380",
            "2796",
            "3331",
            "2021",
            "2022-03-22",
            "12.0000",
            "5160.9300",
            "61931.16",
            "4986.9000",
            "59842.80",
            "59842.80"
          ],
          "rowNumber": 1817741,
          "rowPosition": 1817742,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74679\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817742\" violates the foreign key: for \"id_contrato\": values \"74679\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50293",
            "2",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "22496",
            "1",
            "77",
            "475",
            "14813",
            "90976",
            "364413",
            "74678",
            "889",
            "1831368",
            "2741",
            "1760",
            "2021",
            "2022-02-22",
            "0.0000",
            "295000.0000",
            "295000.00",
            "295000.0000",
            "295000.00",
            "295000.00"
          ],
          "rowNumber": 1818194,
          "rowPosition": 1818195,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74678\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818195\" violates the foreign key: for \"id_contrato\": values \"74678\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50293",
            "2",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "22496",
            "1",
            "77",
            "533",
            "4338",
            "90067",
            "364413",
            "74678",
            "889",
            "1831751",
            "2807",
            "1760",
            "2021",
            "2022-02-22",
            "0.0000",
            "80000.0000",
            "80000.00",
            "80000.0000",
            "80000.00",
            "80000.00"
          ],
          "rowNumber": 1818195,
          "rowPosition": 1818196,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74678\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818196\" violates the foreign key: for \"id_contrato\": values \"74678\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "1",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "28910",
            "1",
            "42",
            "107",
            "19094",
            "151092",
            "366296",
            "74677",
            "889",
            "1831334",
            "2923",
            "2078",
            "2022",
            "2022-03-31",
            "1.0000",
            "3260.0000",
            "3260.00",
            "3260.0000",
            "3260.00",
            "3260.00"
          ],
          "rowNumber": 1824049,
          "rowPosition": 1824050,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824050\" violates the foreign key: for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "1",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "28910",
            "1",
            "42",
            "107",
            "7920",
            "86308",
            "366296",
            "74677",
            "933",
            "1831334",
            "2923",
            "2078",
            "2022",
            "2022-03-31",
            "24.0000",
            "194.0000",
            "4656.00",
            "194.0000",
            "4656.00",
            "4656.00"
          ],
          "rowNumber": 1824050,
          "rowPosition": 1824051,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824051\" violates the foreign key: for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "1",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "28910",
            "1",
            "42",
            "107",
            "19094",
            "168801",
            "366296",
            "74677",
            "890",
            "1831334",
            "2923",
            "2078",
            "2022",
            "2022-03-31",
            "24.0000",
            "1998.0000",
            "47952.00",
            "1998.0000",
            "47952.00",
            "47952.00"
          ],
          "rowNumber": 1824051,
          "rowPosition": 1824052,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824052\" violates the foreign key: for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "1",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "28910",
            "1",
            "42",
            "107",
            "7911",
            "91358",
            "366296",
            "74677",
            "933",
            "1831334",
            "2923",
            "2078",
            "2022",
            "2022-03-31",
            "12.0000",
            "1161.0000",
            "13932.00",
            "1161.0000",
            "13932.00",
            "13932.00"
          ],
          "rowNumber": 1824052,
          "rowPosition": 1824053,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824053\" violates the foreign key: for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "1",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "28910",
            "1",
            "42",
            "107",
            "19094",
            "94550",
            "366296",
            "74677",
            "933",
            "1831334",
            "2923",
            "2078",
            "2022",
            "2022-03-31",
            "12.0000",
            "1161.0000",
            "13932.00",
            "1161.0000",
            "13932.00",
            "13932.00"
          ],
          "rowNumber": 1824053,
          "rowPosition": 1824054,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824054\" violates the foreign key: for \"id_contrato\": values \"74677\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50339",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "72",
            "16014",
            "1",
            "69",
            "416",
            "8259",
            "58316",
            "366230",
            "74687",
            "98",
            "1831312",
            "2608",
            "2925",
            "2022",
            "2022-03-30",
            "6012.0000",
            "45.0000",
            "270540.00",
            "23.0000",
            "138276.00",
            "138276.00"
          ],
          "rowNumber": 1827761,
          "rowPosition": 1827762,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74687\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827762\" violates the foreign key: for \"id_contrato\": values \"74687\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50363",
            "14",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "59725",
            "1",
            "77",
            "719",
            "15485",
            "233944",
            "366611",
            "74683",
            "27",
            "1831369",
            "3144",
            "2839",
            "2022",
            "2022-04-05",
            "0.0000",
            "8753.9000",
            "8753.90",
            "8753.9000",
            "8753.90",
            "8753.90"
          ],
          "rowNumber": 1827788,
          "rowPosition": 1827789,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74683\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827789\" violates the foreign key: for \"id_contrato\": values \"74683\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 116
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 116,
    "tasks": 1
  },
  "valid": false
}