{
  "version": "4.28.0",
  "time": 223.149,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "d6ad47c85d01acb953d778a733a8280c",
          "bytes": 55916143,
          "fields": 27,
          "rows": 1828905
        }
      },
      "time": 223.149,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "50363",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "67288",
            "1",
            "77",
            "533",
            "12280",
            "90758",
            "366011",
            "74720",
            "889",
            "1831724",
            "2599",
            "2000",
            "2022",
            "2022-03-25",
            "0.0000",
            "62374.3000",
            "62374.30",
            "60000.0000",
            "60000.00",
            "60000.00"
          ],
          "rowNumber": 1798539,
          "rowPosition": 1798540,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74720\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798540\" violates the foreign key: for \"id_contrato\": values \"74720\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50338",
            "15",
            "1831015",
            "14",
            "1",
            "1",
            "883",
            "38482",
            "1",
            "3",
            "627",
            "16366",
            "269346",
            "363126",
            "74723",
            "889",
            "1831295",
            "2611",
            "1836",
            "2022",
            "2022-01-31",
            "3.0000",
            "1550.0000",
            "4650.00",
            "1550.0000",
            "4650.00",
            "4650.00"
          ],
          "rowNumber": 1799547,
          "rowPosition": 1799548,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74723\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799548\" violates the foreign key: for \"id_contrato\": values \"74723\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17476",
            "1",
            "13",
            "291",
            "20793",
            "332265",
            "366367",
            "74721",
            "889",
            "1831958",
            "3019",
            "3043",
            "2022",
            "2022-04-01",
            "7.0000",
            "128777.0000",
            "901439.00",
            "128777.0000",
            "901439.00",
            "901439.00"
          ],
          "rowNumber": 1801417,
          "rowPosition": 1801418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74721\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801418\" violates the foreign key: for \"id_contrato\": values \"74721\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50345",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "69276",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "366383",
            "74717",
            "981",
            "1831731",
            "2879",
            "3043",
            "2022",
            "2022-04-01",
            "0.0000",
            "149654.0300",
            "149654.02",
            "94900.0000",
            "94900.00",
            "94900.00"
          ],
          "rowNumber": 1801587,
          "rowPosition": 1801588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74717\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801588\" violates the foreign key: for \"id_contrato\": values \"74717\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50317",
            "15",
            "1831038",
            "24",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "365332",
            "74704",
            "190",
            "1831313",
            "2928",
            "2015",
            "2022",
            "2022-03-15",
            "6000.0000",
            "4.4800",
            "26903.40",
            "4.4800",
            "26903.40",
            "26903.40"
          ],
          "rowNumber": 1801806,
          "rowPosition": 1801807,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74704\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801807\" violates the foreign key: for \"id_contrato\": values \"74704\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50336",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "560",
            "70236",
            "1",
            "69",
            "507",
            "18981",
            "103892",
            "365389",
            "74712",
            "1307",
            "1831312",
            "2538",
            "2082",
            "2022",
            "2022-03-15",
            "100.0000",
            "19.4500",
            "1945.12",
            "19.4500",
            "1945.00",
            "1945.00"
          ],
          "rowNumber": 1802109,
          "rowPosition": 1802110,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74712\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802110\" violates the foreign key: for \"id_contrato\": values \"74712\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50336",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "560",
            "70236",
            "1",
            "69",
            "507",
            "5927",
            "79592",
            "365389",
            "74712",
            "98",
            "1831312",
            "2538",
            "2082",
            "2022",
            "2022-03-15",
            "520.0000",
            "37.8100",
            "19658.60",
            "37.8000",
            "19656.00",
            "19656.00"
          ],
          "rowNumber": 1802110,
          "rowPosition": 1802111,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74712\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802111\" violates the foreign key: for \"id_contrato\": values \"74712\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50336",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "560",
            "70236",
            "1",
            "69",
            "342",
            "16019",
            "18810",
            "365389",
            "74712",
            "1174",
            "1831312",
            "2538",
            "2082",
            "2022",
            "2022-03-15",
            "1040.0000",
            "6.0900",
            "6330.69",
            "6.0800",
            "6323.20",
            "6323.20"
          ],
          "rowNumber": 1802111,
          "rowPosition": 1802112,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74712\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802112\" violates the foreign key: for \"id_contrato\": values \"74712\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50281",
            "13",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "20292",
            "1",
            "8",
            "687",
            "12333",
            "92275",
            "367150",
            "74696",
            "889",
            "1831347",
            "2747",
            "2633",
            "2021",
            "2022-04-12",
            "0.0000",
            "677246.0300",
            "677246.03",
            "659974.6500",
            "659974.65",
            "659974.65"
          ],
          "rowNumber": 1802703,
          "rowPosition": 1802704,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74696\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802704\" violates the foreign key: for \"id_contrato\": values \"74696\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "502",
            "19900",
            "77642",
            "366115",
            "74699",
            "889",
            "1831296",
            "2944",
            "3955",
            "2022",
            "2022-03-28",
            "1.0000",
            "1712.0000",
            "1712.00",
            "1712.0000",
            "1712.00",
            "1712.00"
          ],
          "rowNumber": 1804597,
          "rowPosition": 1804598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74699\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804598\" violates the foreign key: for \"id_contrato\": values \"74699\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "14376",
            "155896",
            "366115",
            "74698",
            "889",
            "1831296",
            "2944",
            "3955",
            "2022",
            "2022-03-28",
            "2.0000",
            "760.0000",
            "1520.00",
            "760.0000",
            "1520.00",
            "1520.00"
          ],
          "rowNumber": 1804598,
          "rowPosition": 1804599,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74698\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804599\" violates the foreign key: for \"id_contrato\": values \"74698\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "776",
            "4035",
            "132250",
            "366115",
            "74698",
            "889",
            "1831296",
            "2944",
            "3955",
            "2022",
            "2022-03-28",
            "4.0000",
            "132.0000",
            "528.00",
            "132.0000",
            "528.00",
            "528.00"
          ],
          "rowNumber": 1804599,
          "rowPosition": 1804600,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74698\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804600\" violates the foreign key: for \"id_contrato\": values \"74698\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "119",
            "17031",
            "142864",
            "366912",
            "74694",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-08",
            "19.0000",
            "2590.0000",
            "49210.00",
            "2590.0000",
            "49210.00",
            "49210.00"
          ],
          "rowNumber": 1807393,
          "rowPosition": 1807394,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74694\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807394\" violates the foreign key: for \"id_contrato\": values \"74694\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "204164",
            "366898",
            "74711",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-08",
            "4.0000",
            "557.0000",
            "2228.00",
            "557.0000",
            "2228.00",
            "2228.00"
          ],
          "rowNumber": 1807394,
          "rowPosition": 1807395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74711\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807395\" violates the foreign key: for \"id_contrato\": values \"74711\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6570",
            "204163",
            "366898",
            "74711",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-08",
            "2.0000",
            "1139.0000",
            "2278.00",
            "1139.0000",
            "2278.00",
            "2278.00"
          ],
          "rowNumber": 1807395,
          "rowPosition": 1807396,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74711\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807396\" violates the foreign key: for \"id_contrato\": values \"74711\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "119",
            "17031",
            "142864",
            "366898",
            "74702",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-08",
            "13.0000",
            "2590.0000",
            "33670.00",
            "2590.0000",
            "33670.00",
            "33670.00"
          ],
          "rowNumber": 1807396,
          "rowPosition": 1807397,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74702\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807397\" violates the foreign key: for \"id_contrato\": values \"74702\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "9",
            "6209",
            "33846",
            "366898",
            "74722",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-08",
            "4.0000",
            "1921.0000",
            "7684.00",
            "1921.0000",
            "7684.00",
            "7684.00"
          ],
          "rowNumber": 1807397,
          "rowPosition": 1807398,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74722\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807398\" violates the foreign key: for \"id_contrato\": values \"74722\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "119",
            "17031",
            "142864",
            "366959",
            "74713",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-08",
            "13.0000",
            "2590.0000",
            "33670.00",
            "2590.0000",
            "33670.00",
            "33670.00"
          ],
          "rowNumber": 1807398,
          "rowPosition": 1807399,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74713\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807399\" violates the foreign key: for \"id_contrato\": values \"74713\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "21",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "329",
            "1",
            "39",
            "130",
            "89",
            "235187",
            "366172",
            "74709",
            "889",
            "1831805",
            "3067",
            "4077",
            "2022",
            "2022-03-29",
            "0.0000",
            "720000.0000",
            "720000.00",
            "720000.0000",
            "720000.00",
            "720000.00"
          ],
          "rowNumber": 1810597,
          "rowPosition": 1810598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74709\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1810598\" violates the foreign key: for \"id_contrato\": values \"74709\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50358",
            "4",
            "1831083",
            "82",
            "1",
            "1",
            "66",
            "34117",
            "1",
            "77",
            "700",
            "7028",
            "162834",
            "366841",
            "74716",
            "889",
            "1831440",
            "2890",
            "2083",
            "2022",
            "2022-04-07",
            "0.0000",
            "14400.0000",
            "14400.00",
            "15786.0000",
            "15786.00",
            "15786.00"
          ],
          "rowNumber": 1813214,
          "rowPosition": 1813215,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74716\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813215\" violates the foreign key: for \"id_contrato\": values \"74716\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49821",
            "2",
            "1831027",
            "22",
            "1",
            "1",
            "337",
            "70855",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "366965",
            "74692",
            "322",
            "1831697",
            "2932",
            "2045",
            "2021",
            "2022-04-11",
            "0.0000",
            "150000.0000",
            "150000.00",
            "150000.0000",
            "150000.00",
            "150000.00"
          ],
          "rowNumber": 1814123,
          "rowPosition": 1814124,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74692\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814124\" violates the foreign key: for \"id_contrato\": values \"74692\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "2",
            "1831083",
            "82",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "710",
            "7497",
            "154634",
            "367014",
            "74714",
            "889",
            "1831812",
            "3065",
            "2083",
            "2022",
            "2022-04-11",
            "0.0000",
            "18000.0000",
            "18000.00",
            "18000.0000",
            "18000.00",
            "18000.00"
          ],
          "rowNumber": 1814124,
          "rowPosition": 1814125,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74714\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814125\" violates the foreign key: for \"id_contrato\": values \"74714\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "2",
            "1831083",
            "82",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "710",
            "7497",
            "150613",
            "367014",
            "74714",
            "889",
            "1831812",
            "3065",
            "2083",
            "2022",
            "2022-04-11",
            "0.0000",
            "41700.0000",
            "41700.00",
            "41700.0000",
            "41700.00",
            "41700.00"
          ],
          "rowNumber": 1814125,
          "rowPosition": 1814126,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74714\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814126\" violates the foreign key: for \"id_contrato\": values \"74714\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50357",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "21210",
            "1",
            "26",
            "824",
            "7408",
            "128621",
            "367039",
            "74697",
            "980",
            "1831233",
            "2863",
            "2014",
            "2022",
            "2022-04-11",
            "500.0000",
            "32.8800",
            "16440.00",
            "32.8800",
            "16440.00",
            "16440.00"
          ],
          "rowNumber": 1814128,
          "rowPosition": 1814129,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74697\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814129\" violates the foreign key: for \"id_contrato\": values \"74697\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48962",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "69742",
            "1",
            "42",
            "399",
            "3867",
            "126616",
            "366573",
            "74715",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-04-04",
            "8400.0000",
            "16.7500",
            "140700.00",
            "4.9000",
            "41160.00",
            "41160.00"
          ],
          "rowNumber": 1814837,
          "rowPosition": 1814838,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74715\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814838\" violates the foreign key: for \"id_contrato\": values \"74715\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50282",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "21643",
            "1",
            "42",
            "399",
            "1194",
            "145115",
            "366894",
            "74718",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-04-08",
            "900.0000",
            "2530.0000",
            "2277000.00",
            "1147.2200",
            "1032498.00",
            "1032498.00"
          ],
          "rowNumber": 1815060,
          "rowPosition": 1815061,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74718\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815061\" violates the foreign key: for \"id_contrato\": values \"74718\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "91625",
            "366574",
            "74707",
            "889",
            "1831737",
            "2869",
            "2014",
            "2022",
            "2022-04-04",
            "0.0000",
            "11073577.0000",
            "11073577.00",
            "11073577.0000",
            "11073577.00",
            "11073577.00"
          ],
          "rowNumber": 1817344,
          "rowPosition": 1817345,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74707\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817345\" violates the foreign key: for \"id_contrato\": values \"74707\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "91625",
            "366574",
            "74707",
            "889",
            "1831737",
            "2869",
            "2014",
            "2022",
            "2022-04-04",
            "0.0000",
            "339327.5000",
            "339327.50",
            "339327.5000",
            "339327.50",
            "339327.50"
          ],
          "rowNumber": 1817345,
          "rowPosition": 1817346,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74707\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817346\" violates the foreign key: for \"id_contrato\": values \"74707\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "91625",
            "366574",
            "74707",
            "889",
            "1831737",
            "2869",
            "2014",
            "2022",
            "2022-04-04",
            "0.0000",
            "176587.5000",
            "176587.50",
            "176587.5000",
            "176587.50",
            "176587.50"
          ],
          "rowNumber": 1817346,
          "rowPosition": 1817347,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74707\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817347\" violates the foreign key: for \"id_contrato\": values \"74707\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831044",
            "36",
            "1",
            "1",
            "318",
            "57991",
            "5",
            "69",
            "740",
            "13114",
            "147581",
            "366882",
            "74689",
            "1174",
            "1831312",
            "2538",
            "2633",
            "2022",
            "2022-04-08",
            "420.0000",
            "23.2000",
            "9744.00",
            "23.2000",
            "9744.00",
            "9744.00"
          ],
          "rowNumber": 1817607,
          "rowPosition": 1817608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74689\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817608\" violates the foreign key: for \"id_contrato\": values \"74689\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "502",
            "14376",
            "128397",
            "366527",
            "74719",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-04",
            "5.0000",
            "1676.0900",
            "8380.45",
            "1676.0900",
            "8380.45",
            "8380.45"
          ],
          "rowNumber": 1819931,
          "rowPosition": 1819932,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74719\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819932\" violates the foreign key: for \"id_contrato\": values \"74719\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43952",
            "14",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "70879",
            "1",
            "77",
            "533",
            "9707",
            "120031",
            "367244",
            "74724",
            "889",
            "1831531",
            "2669",
            "2840",
            "2022",
            "2022-04-14",
            "0.0000",
            "5430.0400",
            "5430.04",
            "5430.0400",
            "5430.04",
            "5430.04"
          ],
          "rowNumber": 1820064,
          "rowPosition": 1820065,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367244\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"1820065\" violates the foreign key: for \"id_processo\": values \"367244\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43952",
            "14",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "70879",
            "1",
            "77",
            "533",
            "9707",
            "120031",
            "367244",
            "74724",
            "889",
            "1831531",
            "2669",
            "2840",
            "2022",
            "2022-04-14",
            "0.0000",
            "5430.0400",
            "5430.04",
            "5430.0400",
            "5430.04",
            "5430.04"
          ],
          "rowNumber": 1820064,
          "rowPosition": 1820065,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74724\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820065\" violates the foreign key: for \"id_contrato\": values \"74724\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43952",
            "14",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "70879",
            "1",
            "77",
            "533",
            "9707",
            "120031",
            "367244",
            "74724",
            "889",
            "1831531",
            "2669",
            "2840",
            "2022",
            "2022-04-14",
            "0.0000",
            "5430.0400",
            "5430.04",
            "5430.0400",
            "5430.04",
            "5430.04"
          ],
          "rowNumber": 1820064,
          "rowPosition": 1820065,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"70879\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1820065\" violates the foreign key: for \"id_contratado\": values \"70879\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50300",
            "2",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "19679",
            "1",
            "77",
            "475",
            "14801",
            "115049",
            "365164",
            "74705",
            "889",
            "1831368",
            "2741",
            "2045",
            "2021",
            "2022-03-11",
            "0.0000",
            "376912.5000",
            "376912.50",
            "376912.5000",
            "376912.50",
            "376912.50"
          ],
          "rowNumber": 1821426,
          "rowPosition": 1821427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74705\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821427\" violates the foreign key: for \"id_contrato\": values \"74705\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "15",
            "1831100",
            "99",
            "1",
            "1",
            "844",
            "3000",
            "1",
            "54",
            "502",
            "14497",
            "146901",
            "366031",
            "74703",
            "889",
            "1831296",
            "2944",
            "3331",
            "2022",
            "2022-03-25",
            "4.0000",
            "449.0000",
            "1796.00",
            "449.0000",
            "1796.00",
            "1796.00"
          ],
          "rowNumber": 1823782,
          "rowPosition": 1823783,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74703\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823783\" violates the foreign key: for \"id_contrato\": values \"74703\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "15",
            "1831100",
            "99",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "144721",
            "366031",
            "74691",
            "889",
            "1831296",
            "2944",
            "3331",
            "2022",
            "2022-03-25",
            "3.0000",
            "768.0000",
            "2304.00",
            "768.0000",
            "2304.00",
            "2304.00"
          ],
          "rowNumber": 1823783,
          "rowPosition": 1823784,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74691\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823784\" violates the foreign key: for \"id_contrato\": values \"74691\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "15",
            "1831100",
            "99",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "17171",
            "124786",
            "366031",
            "74688",
            "889",
            "1831296",
            "2944",
            "3331",
            "2022",
            "2022-03-25",
            "4.0000",
            "440.0000",
            "1760.00",
            "440.0000",
            "1760.00",
            "1760.00"
          ],
          "rowNumber": 1823784,
          "rowPosition": 1823785,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74688\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823785\" violates the foreign key: for \"id_contrato\": values \"74688\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "15",
            "1831100",
            "99",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "14376",
            "155896",
            "366031",
            "74688",
            "889",
            "1831296",
            "2944",
            "3331",
            "2022",
            "2022-03-25",
            "1.0000",
            "760.0000",
            "760.00",
            "760.0000",
            "760.00",
            "760.00"
          ],
          "rowNumber": 1823785,
          "rowPosition": 1823786,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74688\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823786\" violates the foreign key: for \"id_contrato\": values \"74688\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "15",
            "1831083",
            "82",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226216",
            "366041",
            "74710",
            "889",
            "1831295",
            "2611",
            "2083",
            "2022",
            "2022-03-25",
            "400.0000",
            "4217.5700",
            "1687028.00",
            "4217.5700",
            "1687028.00",
            "1687028.00"
          ],
          "rowNumber": 1823797,
          "rowPosition": 1823798,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74710\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823798\" violates the foreign key: for \"id_contrato\": values \"74710\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50363",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "67288",
            "1",
            "77",
            "533",
            "12280",
            "90758",
            "366023",
            "74720",
            "889",
            "1831724",
            "2599",
            "3043",
            "2022",
            "2022-03-25",
            "0.0000",
            "93561.4500",
            "93561.45",
            "90000.0000",
            "90000.00",
            "90000.00"
          ],
          "rowNumber": 1823812,
          "rowPosition": 1823813,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74720\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823813\" violates the foreign key: for \"id_contrato\": values \"74720\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50273",
            "4",
            "1831083",
            "82",
            "1",
            "1",
            "824",
            "16328",
            "1",
            "17",
            "379",
            "17564",
            "110037",
            "366356",
            "74706",
            "889",
            "1831370",
            "2594",
            "2083",
            "2021",
            "2022-03-31",
            "0.0000",
            "33861.0200",
            "33861.02",
            "35001.7800",
            "35001.78",
            "35001.78"
          ],
          "rowNumber": 1824439,
          "rowPosition": 1824440,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74706\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824440\" violates the foreign key: for \"id_contrato\": values \"74706\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "856",
            "21226",
            "1",
            "13",
            "291",
            "20788",
            "240926",
            "366310",
            "74708",
            "889",
            "1831958",
            "3019",
            "3043",
            "2022",
            "2022-03-31",
            "1.0000",
            "254220.0000",
            "254220.00",
            "254220.0000",
            "254220.00",
            "254220.00"
          ],
          "rowNumber": 1824825,
          "rowPosition": 1824826,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74708\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824826\" violates the foreign key: for \"id_contrato\": values \"74708\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50349",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "732",
            "21630",
            "171137",
            "366660",
            "74693",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-04-05",
            "1000.0000",
            "153.0000",
            "153000.00",
            "139.0000",
            "139000.00",
            "139000.00"
          ],
          "rowNumber": 1825980,
          "rowPosition": 1825981,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74693\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825981\" violates the foreign key: for \"id_contrato\": values \"74693\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50349",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "732",
            "21596",
            "170228",
            "366660",
            "74693",
            "591",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-04-05",
            "1935.0000",
            "54.0700",
            "104625.45",
            "50.1800",
            "97098.30",
            "97098.30"
          ],
          "rowNumber": 1825981,
          "rowPosition": 1825982,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74693\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825982\" violates the foreign key: for \"id_contrato\": values \"74693\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50266",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "15059",
            "1",
            "51",
            "383",
            "17638",
            "94053",
            "365637",
            "74700",
            "981",
            "1831360",
            "2670",
            "2014",
            "2021",
            "2022-03-18",
            "0.0000",
            "48000.0000",
            "48000.00",
            "29899.9200",
            "29899.92",
            "29899.92"
          ],
          "rowNumber": 1828029,
          "rowPosition": 1828030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74700\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828030\" violates the foreign key: for \"id_contrato\": values \"74700\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50339",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "72",
            "70628",
            "1",
            "69",
            "416",
            "8066",
            "52235",
            "366230",
            "74701",
            "98",
            "1831312",
            "2608",
            "2925",
            "2022",
            "2022-03-30",
            "4008.0000",
            "17.6000",
            "70540.80",
            "16.0000",
            "64128.00",
            "64128.00"
          ],
          "rowNumber": 1828338,
          "rowPosition": 1828339,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74701\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828339\" violates the foreign key: for \"id_contrato\": values \"74701\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50335",
            "1",
            "1831067",
            "64",
            "1",
            "1",
            "883",
            "1547",
            "1",
            "77",
            "533",
            "12661",
            "116531",
            "365565",
            "74690",
            "889",
            "1831910",
            "2738",
            "2885",
            "2022",
            "2022-03-18",
            "0.0000",
            "1310181.5200",
            "1310181.52",
            "1310181.5200",
            "1310181.52",
            "1310181.52"
          ],
          "rowNumber": 1828359,
          "rowPosition": 1828360,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74690\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828360\" violates the foreign key: for \"id_contrato\": values \"74690\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50335",
            "1",
            "1831067",
            "64",
            "1",
            "1",
            "883",
            "1547",
            "1",
            "77",
            "533",
            "12661",
            "207831",
            "365565",
            "74690",
            "889",
            "1831910",
            "2738",
            "2885",
            "2022",
            "2022-03-18",
            "0.0000",
            "1310181.5300",
            "1310181.53",
            "1310181.5300",
            "1310181.53",
            "1310181.53"
          ],
          "rowNumber": 1828360,
          "rowPosition": 1828361,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74690\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828361\" violates the foreign key: for \"id_contrato\": values \"74690\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50335",
            "1",
            "1831067",
            "64",
            "1",
            "1",
            "883",
            "1547",
            "1",
            "77",
            "533",
            "12661",
            "116532",
            "365565",
            "74690",
            "889",
            "1831910",
            "2738",
            "2885",
            "2022",
            "2022-03-18",
            "0.0000",
            "1310181.5200",
            "1310181.52",
            "1310181.5200",
            "1310181.52",
            "1310181.52"
          ],
          "rowNumber": 1828361,
          "rowPosition": 1828362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74690\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828362\" violates the foreign key: for \"id_contrato\": values \"74690\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "17605",
            "1",
            "60",
            "652",
            "3745",
            "35169",
            "366271",
            "74695",
            "889",
            "1831952",
            "2995",
            "3293",
            "2022",
            "2022-03-30",
            "100.0000",
            "0.5500",
            "55.00",
            "0.5500",
            "55.00",
            "55.00"
          ],
          "rowNumber": 1828840,
          "rowPosition": 1828841,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828841\" violates the foreign key: for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "17605",
            "1",
            "60",
            "652",
            "19521",
            "35146",
            "366271",
            "74695",
            "889",
            "1831952",
            "2995",
            "3293",
            "2022",
            "2022-03-30",
            "100.0000",
            "1.4500",
            "145.00",
            "1.4500",
            "145.00",
            "145.00"
          ],
          "rowNumber": 1828841,
          "rowPosition": 1828842,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828842\" violates the foreign key: for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "17605",
            "1",
            "60",
            "652",
            "17915",
            "147820",
            "366271",
            "74695",
            "889",
            "1831952",
            "2995",
            "3293",
            "2022",
            "2022-03-30",
            "50.0000",
            "131.6600",
            "6583.00",
            "131.6600",
            "6583.00",
            "6583.00"
          ],
          "rowNumber": 1828842,
          "rowPosition": 1828843,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828843\" violates the foreign key: for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "17605",
            "1",
            "60",
            "652",
            "811",
            "19224",
            "366271",
            "74695",
            "889",
            "1831952",
            "2995",
            "3293",
            "2022",
            "2022-03-30",
            "100.0000",
            "1.3800",
            "138.00",
            "1.3800",
            "138.00",
            "138.00"
          ],
          "rowNumber": 1828843,
          "rowPosition": 1828844,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828844\" violates the foreign key: for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "17605",
            "1",
            "60",
            "652",
            "1217",
            "147428",
            "366271",
            "74695",
            "889",
            "1831952",
            "2995",
            "3293",
            "2022",
            "2022-03-30",
            "150.0000",
            "188.7900",
            "28318.50",
            "188.7900",
            "28318.50",
            "28318.50"
          ],
          "rowNumber": 1828844,
          "rowPosition": 1828845,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828845\" violates the foreign key: for \"id_contrato\": values \"74695\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 55
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 55,
    "tasks": 1
  },
  "valid": false
}