{
  "version": "4.28.0",
  "time": 229.873,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "3a16f2f0c6daad1d80c30ee6c147a920",
          "bytes": 56134460,
          "fields": 27,
          "rows": 1836369
        }
      },
      "time": 229.873,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "49902",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "233",
            "25519",
            "1",
            "51",
            "75",
            "12410",
            "166539",
            "368022",
            "75056",
            "889",
            "1831642",
            "2594",
            "2633",
            "2021",
            "2022-04-29",
            "0.0000",
            "460644.5600",
            "460644.56",
            "400000.0000",
            "400000.00",
            "400000.00"
          ],
          "rowNumber": 1799774,
          "rowPosition": 1799775,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75056\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799775\" violates the foreign key: for \"id_contrato\": values \"75056\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "39651",
            "1",
            "89",
            "778",
            "10128",
            "338002",
            "368087",
            "75021",
            "889",
            "1831991",
            "2743",
            "3043",
            "2022",
            "2022-04-29",
            "1040.0000",
            "1050.8300",
            "1092863.20",
            "1050.8300",
            "1092863.20",
            "1092863.20"
          ],
          "rowNumber": 1800109,
          "rowPosition": 1800110,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75021\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800110\" violates the foreign key: for \"id_contrato\": values \"75021\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "39651",
            "1",
            "89",
            "778",
            "10128",
            "338790",
            "368087",
            "75021",
            "889",
            "1831991",
            "2743",
            "3043",
            "2022",
            "2022-04-29",
            "65.0000",
            "8989.0000",
            "584285.00",
            "8989.0000",
            "584285.00",
            "584285.00"
          ],
          "rowNumber": 1800110,
          "rowPosition": 1800111,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75021\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800111\" violates the foreign key: for \"id_contrato\": values \"75021\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43981",
            "15",
            "1831046",
            "43",
            "1",
            "1",
            "883",
            "20857",
            "1",
            "39",
            "834",
            "21813",
            "206336",
            "368007",
            "75035",
            "889",
            "1831739",
            "3067",
            "2696",
            "2022",
            "2022-04-29",
            "1.0000",
            "4088.0000",
            "4088.00",
            "4088.0000",
            "4088.00",
            "4088.00"
          ],
          "rowNumber": 1800112,
          "rowPosition": 1800113,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75035\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800113\" violates the foreign key: for \"id_contrato\": values \"75035\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50349",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "13878",
            "1",
            "77",
            "808",
            "4383",
            "199499",
            "368029",
            "75040",
            "889",
            "1831737",
            "2869",
            "3293",
            "2022",
            "2022-04-29",
            "0.0000",
            "778175.0000",
            "778175.00",
            "666359.9600",
            "666359.96",
            "666359.96"
          ],
          "rowNumber": 1800115,
          "rowPosition": 1800116,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75040\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800116\" violates the foreign key: for \"id_contrato\": values \"75040\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50365",
            "13",
            "1831042",
            "42",
            "1",
            "1",
            "66",
            "70894",
            "1",
            "41",
            "806",
            "14879",
            "307010",
            "368000",
            "75037",
            "889",
            "1831346",
            "2891",
            "2267",
            "2022",
            "2022-04-29",
            "0.0000",
            "50970.0000",
            "50970.00",
            "10561.7100",
            "10561.71",
            "10561.71"
          ],
          "rowNumber": 1800467,
          "rowPosition": 1800468,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75037\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800468\" violates the foreign key: for \"id_contrato\": values \"75037\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50365",
            "13",
            "1831042",
            "42",
            "1",
            "1",
            "66",
            "70894",
            "1",
            "41",
            "806",
            "14879",
            "141516",
            "368000",
            "75037",
            "889",
            "1831346",
            "2891",
            "2267",
            "2022",
            "2022-04-29",
            "0.0000",
            "92891.2600",
            "92891.26",
            "117759.5800",
            "117759.58",
            "117759.58"
          ],
          "rowNumber": 1800468,
          "rowPosition": 1800469,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75037\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800469\" violates the foreign key: for \"id_contrato\": values \"75037\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50365",
            "13",
            "1831042",
            "42",
            "1",
            "1",
            "66",
            "70894",
            "1",
            "41",
            "806",
            "14879",
            "305555",
            "368000",
            "75037",
            "889",
            "1831346",
            "2891",
            "2267",
            "2022",
            "2022-04-29",
            "0.0000",
            "126545.9200",
            "126545.92",
            "141863.6000",
            "141863.60",
            "141863.60"
          ],
          "rowNumber": 1800469,
          "rowPosition": 1800470,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75037\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800470\" violates the foreign key: for \"id_contrato\": values \"75037\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "1",
            "1831093",
            "101",
            "1",
            "1",
            "66",
            "17168",
            "1",
            "77",
            "73",
            "1896",
            "92642",
            "368126",
            "75027",
            "889",
            "1831565",
            "3000",
            "2720",
            "2022",
            "2022-05-02",
            "0.0000",
            "8000.0000",
            "8000.00",
            "8000.0000",
            "8000.00",
            "8000.00"
          ],
          "rowNumber": 1804436,
          "rowPosition": 1804437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75027\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804437\" violates the foreign key: for \"id_contrato\": values \"75027\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "877",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "13759.8000",
            "13759.80",
            "13759.8000",
            "13759.80",
            "13759.80"
          ],
          "rowNumber": 1804727,
          "rowPosition": 1804728,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804728\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "877",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "240796.5000",
            "240796.50",
            "240796.5000",
            "240796.50",
            "240796.50"
          ],
          "rowNumber": 1804728,
          "rowPosition": 1804729,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804729\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "877",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90058",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "4496.0300",
            "4496.03",
            "4496.0300",
            "4496.03",
            "4496.03"
          ],
          "rowNumber": 1804729,
          "rowPosition": 1804730,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804730\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "877",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "91084",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "40464.2700",
            "40464.27",
            "40464.2700",
            "40464.27",
            "40464.27"
          ],
          "rowNumber": 1804730,
          "rowPosition": 1804731,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804731\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "200893.0800",
            "200893.08",
            "200893.0800",
            "200893.08",
            "200893.08"
          ],
          "rowNumber": 1804732,
          "rowPosition": 1804733,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804733\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "13071.8100",
            "13071.81",
            "13071.8000",
            "13071.80",
            "13071.80"
          ],
          "rowNumber": 1804733,
          "rowPosition": 1804734,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804734\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "24517.9200",
            "24517.92",
            "24517.9200",
            "24517.92",
            "24517.92"
          ],
          "rowNumber": 1804734,
          "rowPosition": 1804735,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804735\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "835",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "17199.7500",
            "17199.75",
            "17199.7500",
            "17199.75",
            "17199.75"
          ],
          "rowNumber": 1804737,
          "rowPosition": 1804738,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804738\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "835",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "3439.9500",
            "3439.95",
            "3439.9500",
            "3439.95",
            "3439.95"
          ],
          "rowNumber": 1804738,
          "rowPosition": 1804739,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804739\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "835",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "14302.1200",
            "14302.12",
            "14302.1200",
            "14302.12",
            "14302.12"
          ],
          "rowNumber": 1804739,
          "rowPosition": 1804740,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804740\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "419",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "2751.9600",
            "2751.96",
            "2751.9600",
            "2751.96",
            "2751.96"
          ],
          "rowNumber": 1804740,
          "rowPosition": 1804741,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804741\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "419",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "7005.1200",
            "7005.12",
            "7005.1200",
            "7005.12",
            "7005.12"
          ],
          "rowNumber": 1804741,
          "rowPosition": 1804742,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804742\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "357",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "1751.2800",
            "1751.28",
            "1751.2800",
            "1751.28",
            "1751.28"
          ],
          "rowNumber": 1804742,
          "rowPosition": 1804743,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804743\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "357",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "9631.8600",
            "9631.86",
            "9631.8600",
            "9631.86",
            "9631.86"
          ],
          "rowNumber": 1804743,
          "rowPosition": 1804744,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804744\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "315",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "13759.8000",
            "13759.80",
            "13759.8000",
            "13759.80",
            "13759.80"
          ],
          "rowNumber": 1804744,
          "rowPosition": 1804745,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804745\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "315",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "5503.9200",
            "5503.92",
            "5503.9200",
            "5503.92",
            "5503.92"
          ],
          "rowNumber": 1804745,
          "rowPosition": 1804746,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804746\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "315",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "5253.8400",
            "5253.84",
            "5253.8400",
            "5253.84",
            "5253.84"
          ],
          "rowNumber": 1804746,
          "rowPosition": 1804747,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804747\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "248",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "2918.8000",
            "2918.80",
            "2918.8000",
            "2918.80",
            "2918.80"
          ],
          "rowNumber": 1804747,
          "rowPosition": 1804748,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804748\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "206",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "875.6400",
            "875.64",
            "875.6400",
            "875.64",
            "875.64"
          ],
          "rowNumber": 1804748,
          "rowPosition": 1804749,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804749\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "206",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "2751.9600",
            "2751.96",
            "2751.9600",
            "2751.96",
            "2751.96"
          ],
          "rowNumber": 1804749,
          "rowPosition": 1804750,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804750\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "1375.9800",
            "1375.98",
            "1375.9800",
            "1375.98",
            "1375.98"
          ],
          "rowNumber": 1804750,
          "rowPosition": 1804751,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804751\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "5503.9200",
            "5503.92",
            "5503.9200",
            "5503.92",
            "5503.92"
          ],
          "rowNumber": 1804751,
          "rowPosition": 1804752,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804752\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "2918.8000",
            "2918.80",
            "2918.8000",
            "2918.80",
            "2918.80"
          ],
          "rowNumber": 1804752,
          "rowPosition": 1804753,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804753\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "825",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "81870.8100",
            "81870.81",
            "81870.8100",
            "81870.81",
            "81870.81"
          ],
          "rowNumber": 1804753,
          "rowPosition": 1804754,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804754\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "825",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "8756.4000",
            "8756.40",
            "8756.4000",
            "8756.40",
            "8756.40"
          ],
          "rowNumber": 1804754,
          "rowPosition": 1804755,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804755\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "825",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "18575.7300",
            "18575.73",
            "18575.7300",
            "18575.73",
            "18575.73"
          ],
          "rowNumber": 1804755,
          "rowPosition": 1804756,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804756\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "824",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "4127.9400",
            "4127.94",
            "4127.9400",
            "4127.94",
            "4127.94"
          ],
          "rowNumber": 1804756,
          "rowPosition": 1804757,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804757\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "824",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "41279.4000",
            "41279.40",
            "41279.4000",
            "41279.40",
            "41279.40"
          ],
          "rowNumber": 1804757,
          "rowPosition": 1804758,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804758\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "824",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "1459.4000",
            "1459.40",
            "1459.4000",
            "1459.40",
            "1459.40"
          ],
          "rowNumber": 1804758,
          "rowPosition": 1804759,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804759\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "501",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "3794.4400",
            "3794.44",
            "3794.4400",
            "3794.44",
            "3794.44"
          ],
          "rowNumber": 1804759,
          "rowPosition": 1804760,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1804760\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "501",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "30271.5600",
            "30271.56",
            "30271.5600",
            "30271.56",
            "30271.56"
          ],
          "rowNumber": 1805046,
          "rowPosition": 1805047,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805047\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "501",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "1375.9800",
            "1375.98",
            "1375.9800",
            "1375.98",
            "1375.98"
          ],
          "rowNumber": 1805047,
          "rowPosition": 1805048,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805048\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "4",
            "1831083",
            "82",
            "1",
            "1",
            "66",
            "7525",
            "1",
            "32",
            "100",
            "4654",
            "316949",
            "367836",
            "75043",
            "889",
            "1831400",
            "2796",
            "2083",
            "2022",
            "2022-04-27",
            "4.0000",
            "17517.2300",
            "70068.92",
            "12538.0000",
            "50152.00",
            "50152.00"
          ],
          "rowNumber": 1805331,
          "rowPosition": 1805332,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75043\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805332\" violates the foreign key: for \"id_contrato\": values \"75043\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "89",
            "535",
            "382",
            "274505",
            "368674",
            "75031",
            "889",
            "1831991",
            "2746",
            "1760",
            "2022",
            "2022-05-09",
            "17.0000",
            "400.0000",
            "6800.00",
            "400.0000",
            "6800.00",
            "6800.00"
          ],
          "rowNumber": 1806027,
          "rowPosition": 1806028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806028\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "89",
            "535",
            "382",
            "274492",
            "368674",
            "75031",
            "889",
            "1831991",
            "2746",
            "1760",
            "2022",
            "2022-05-09",
            "12.0000",
            "900.0000",
            "10800.00",
            "900.0000",
            "10800.00",
            "10800.00"
          ],
          "rowNumber": 1806028,
          "rowPosition": 1806029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806029\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "89",
            "535",
            "382",
            "272121",
            "368674",
            "75031",
            "889",
            "1831991",
            "2746",
            "1760",
            "2022",
            "2022-05-09",
            "12.0000",
            "900.0000",
            "10800.00",
            "900.0000",
            "10800.00",
            "10800.00"
          ],
          "rowNumber": 1806029,
          "rowPosition": 1806030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806030\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "89",
            "535",
            "382",
            "274493",
            "368674",
            "75031",
            "889",
            "1831991",
            "2746",
            "1760",
            "2022",
            "2022-05-09",
            "3.0000",
            "3500.0000",
            "10500.00",
            "3500.0000",
            "10500.00",
            "10500.00"
          ],
          "rowNumber": 1806030,
          "rowPosition": 1806031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806031\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "89",
            "535",
            "2311",
            "170043",
            "368674",
            "75031",
            "889",
            "1831991",
            "2746",
            "1760",
            "2022",
            "2022-05-09",
            "13.0000",
            "1000.0000",
            "13000.00",
            "1000.0000",
            "13000.00",
            "13000.00"
          ],
          "rowNumber": 1806031,
          "rowPosition": 1806032,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806032\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "89",
            "535",
            "382",
            "194797",
            "368674",
            "75031",
            "889",
            "1831991",
            "2746",
            "1760",
            "2022",
            "2022-05-09",
            "25.0000",
            "220.0000",
            "5500.00",
            "220.0000",
            "5500.00",
            "5500.00"
          ],
          "rowNumber": 1806032,
          "rowPosition": 1806033,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806033\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "3",
            "143",
            "18489",
            "272110",
            "368674",
            "75031",
            "889",
            "1831295",
            "2746",
            "1760",
            "2022",
            "2022-05-09",
            "4.0000",
            "600.0000",
            "2400.00",
            "600.0000",
            "2400.00",
            "2400.00"
          ],
          "rowNumber": 1806033,
          "rowPosition": 1806034,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806034\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44005",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "17683",
            "1",
            "51",
            "276",
            "17607",
            "92312",
            "368674",
            "75031",
            "889",
            "1831624",
            "2670",
            "1760",
            "2022",
            "2022-05-09",
            "0.0000",
            "147900.0000",
            "147900.00",
            "147900.0000",
            "147900.00",
            "147900.00"
          ],
          "rowNumber": 1806034,
          "rowPosition": 1806035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806035\" violates the foreign key: for \"id_contrato\": values \"75031\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "8255.8800",
            "8255.88",
            "8255.8800",
            "8255.88",
            "8255.88"
          ],
          "rowNumber": 1806035,
          "rowPosition": 1806036,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1806036\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44003",
            "1",
            "1831071",
            "50",
            "1",
            "8",
            "361",
            "71040",
            "1",
            "77",
            "479",
            "4462",
            "92603",
            "368580",
            "36233",
            "889",
            "1831808",
            "3144",
            "3267",
            "2022",
            "2022-05-09",
            "0.0000",
            "10000.0000",
            "10000.00",
            "10000.0000",
            "10000.00",
            "10000.00"
          ],
          "rowNumber": 1806049,
          "rowPosition": 1806050,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71040\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1806050\" violates the foreign key: for \"id_contratado\": values \"71040\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50293",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "69728",
            "1",
            "51",
            "274",
            "12408",
            "92929",
            "366077",
            "75053",
            "889",
            "1831357",
            "2594",
            "2838",
            "2021",
            "2022-03-28",
            "0.0000",
            "62300.7500",
            "62300.75",
            "42000.0000",
            "42000.00",
            "42000.00"
          ],
          "rowNumber": 1807010,
          "rowPosition": 1807011,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75053\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807011\" violates the foreign key: for \"id_contrato\": values \"75053\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "1",
            "1831092",
            "50",
            "1",
            "8",
            "357",
            "71038",
            "1",
            "9",
            "576",
            "1923",
            "93139",
            "368670",
            "36233",
            "1511",
            "1831678",
            "2738",
            "2005",
            "2022",
            "2022-05-09",
            "0.0000",
            "9280.0000",
            "9280.00",
            "9280.0000",
            "9280.00",
            "9280.00"
          ],
          "rowNumber": 1809763,
          "rowPosition": 1809764,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71038\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1809764\" violates the foreign key: for \"id_contratado\": values \"71038\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "4127.9400",
            "4127.94",
            "4127.9400",
            "4127.94",
            "4127.94"
          ],
          "rowNumber": 1809764,
          "rowPosition": 1809765,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809765\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "877",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "6879.9000",
            "6879.90",
            "6879.9000",
            "6879.90",
            "6879.90"
          ],
          "rowNumber": 1809765,
          "rowPosition": 1809766,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809766\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "877",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "171997.5000",
            "171997.50",
            "171997.5000",
            "171997.50",
            "171997.50"
          ],
          "rowNumber": 1809766,
          "rowPosition": 1809767,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809767\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "877",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "5837.6000",
            "5837.60",
            "5837.6000",
            "5837.60",
            "5837.60"
          ],
          "rowNumber": 1809767,
          "rowPosition": 1809768,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809768\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "44031.3600",
            "44031.36",
            "44031.3600",
            "44031.36",
            "44031.36"
          ],
          "rowNumber": 1809768,
          "rowPosition": 1809769,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809769\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "33023.5200",
            "33023.52",
            "33023.5200",
            "33023.52",
            "33023.52"
          ],
          "rowNumber": 1809769,
          "rowPosition": 1809770,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809770\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "5503.9200",
            "5503.92",
            "5503.9200",
            "5503.92",
            "5503.92"
          ],
          "rowNumber": 1809770,
          "rowPosition": 1809771,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809771\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "583.7600",
            "583.76",
            "583.7600",
            "583.76",
            "583.76"
          ],
          "rowNumber": 1809771,
          "rowPosition": 1809772,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809772\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "583.7600",
            "583.76",
            "583.7600",
            "583.76",
            "583.76"
          ],
          "rowNumber": 1809773,
          "rowPosition": 1809774,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809774\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "16511.7600",
            "16511.76",
            "16511.7600",
            "16511.76",
            "16511.76"
          ],
          "rowNumber": 1809774,
          "rowPosition": 1809775,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809775\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "13759.8000",
            "13759.80",
            "13759.8000",
            "13759.80",
            "13759.80"
          ],
          "rowNumber": 1809775,
          "rowPosition": 1809776,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809776\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831096",
            "92",
            "1",
            "2",
            "66",
            "17435",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "368666",
            "75044",
            "889",
            "1831724",
            "2772",
            "2631",
            "2022",
            "2022-05-09",
            "0.0000",
            "1375.9800",
            "1375.98",
            "1375.9800",
            "1375.98",
            "1375.98"
          ],
          "rowNumber": 1809776,
          "rowPosition": 1809777,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1809777\" violates the foreign key: for \"id_contrato\": values \"75044\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50332",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "315",
            "34107",
            "1",
            "77",
            "808",
            "4383",
            "199499",
            "366844",
            "75048",
            "889",
            "1831737",
            "2869",
            "3293",
            "2022",
            "2022-04-07",
            "0.0000",
            "8378250.9000",
            "8378250.90",
            "6723198.3000",
            "6723198.30",
            "6723198.30"
          ],
          "rowNumber": 1816886,
          "rowPosition": 1816887,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75048\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816887\" violates the foreign key: for \"id_contrato\": values \"75048\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "121326",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "74278.0000",
            "37.5400",
            "2788099.01",
            "37.5400",
            "2788099.00",
            "2788099.00"
          ],
          "rowNumber": 1816917,
          "rowPosition": 1816918,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816918\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "92001",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "101423.0000",
            "32.7400",
            "3320183.33",
            "32.7400",
            "3320183.32",
            "3320183.32"
          ],
          "rowNumber": 1816918,
          "rowPosition": 1816919,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816919\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "121325",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "11329.0000",
            "31.2500",
            "354008.59",
            "31.2500",
            "354008.59",
            "354008.59"
          ],
          "rowNumber": 1816919,
          "rowPosition": 1816920,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816920\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "317921",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "184181.0000",
            "9.0400",
            "1665585.62",
            "9.0400",
            "1665585.61",
            "1665585.61"
          ],
          "rowNumber": 1816920,
          "rowPosition": 1816921,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816921\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "121327",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "5046.0000",
            "23.9900",
            "121055.56",
            "23.9900",
            "121055.55",
            "121055.55"
          ],
          "rowNumber": 1816921,
          "rowPosition": 1816922,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816922\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "121323",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "74.0000",
            "6.3200",
            "467.44",
            "6.3200",
            "467.44",
            "467.44"
          ],
          "rowNumber": 1816922,
          "rowPosition": 1816923,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816923\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "121517",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "27250.0000",
            "3.9100",
            "106471.20",
            "3.9100",
            "106471.20",
            "106471.20"
          ],
          "rowNumber": 1816923,
          "rowPosition": 1816924,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816924\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "121322",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "497.0000",
            "25.4300",
            "12638.96",
            "25.4300",
            "12638.95",
            "12638.95"
          ],
          "rowNumber": 1816924,
          "rowPosition": 1816925,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816925\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "161854",
            "366176",
            "75039",
            "1883",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "10.0000",
            "3.2400",
            "32.45",
            "3.2400",
            "32.44",
            "32.44"
          ],
          "rowNumber": 1816925,
          "rowPosition": 1816926,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816926\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "121518",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "25799.0000",
            "7.7300",
            "199374.67",
            "7.7300",
            "199374.67",
            "199374.67"
          ],
          "rowNumber": 1816926,
          "rowPosition": 1816927,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816927\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19635",
            "1",
            "77",
            "808",
            "4383",
            "144293",
            "366176",
            "75039",
            "889",
            "1831737",
            "2869",
            "2925",
            "2022",
            "2022-03-29",
            "478.0000",
            "4.8400",
            "2312.76",
            "4.8400",
            "2312.75",
            "2312.75"
          ],
          "rowNumber": 1816927,
          "rowPosition": 1816928,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816928\" violates the foreign key: for \"id_contrato\": values \"75039\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43976",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "776",
            "4035",
            "132250",
            "366967",
            "75020",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-04-11",
            "1.0000",
            "132.0000",
            "132.00",
            "132.0000",
            "132.00",
            "132.00"
          ],
          "rowNumber": 1818678,
          "rowPosition": 1818679,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75020\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818679\" violates the foreign key: for \"id_contrato\": values \"75020\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43945",
            "2",
            "1831055",
            "51",
            "1",
            "1",
            "877",
            "31915",
            "1",
            "39",
            "130",
            "1824",
            "98675",
            "366922",
            "75038",
            "889",
            "1831812",
            "3065",
            "2523",
            "2022",
            "2022-04-08",
            "0.0000",
            "231128.0000",
            "231128.00",
            "231128.0000",
            "231128.00",
            "231128.00"
          ],
          "rowNumber": 1818769,
          "rowPosition": 1818770,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75038\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818770\" violates the foreign key: for \"id_contrato\": values \"75038\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "507",
            "35287",
            "1",
            "51",
            "374",
            "20260",
            "93214",
            "367474",
            "75055",
            "26",
            "1831362",
            "2545",
            "2413",
            "2022",
            "2022-04-19",
            "0.0000",
            "44122.0000",
            "44122.00",
            "44122.0000",
            "44122.00",
            "44122.00"
          ],
          "rowNumber": 1824151,
          "rowPosition": 1824152,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75055\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824152\" violates the foreign key: for \"id_contrato\": values \"75055\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "507",
            "35287",
            "1",
            "51",
            "374",
            "20260",
            "93213",
            "367474",
            "75055",
            "26",
            "1831362",
            "2545",
            "2413",
            "2022",
            "2022-04-19",
            "0.0000",
            "16208.0000",
            "16208.00",
            "16208.0000",
            "16208.00",
            "16208.00"
          ],
          "rowNumber": 1824152,
          "rowPosition": 1824153,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75055\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824153\" violates the foreign key: for \"id_contrato\": values \"75055\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "14",
            "1831105",
            "91",
            "1",
            "1",
            "436",
            "55810",
            "1",
            "77",
            "700",
            "20204",
            "92477",
            "367475",
            "75034",
            "889",
            "1831443",
            "2954",
            "3042",
            "2022",
            "2022-04-19",
            "0.0000",
            "15600.0000",
            "15600.00",
            "15600.0000",
            "15600.00",
            "15600.00"
          ],
          "rowNumber": 1824158,
          "rowPosition": 1824159,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75034\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824159\" violates the foreign key: for \"id_contrato\": values \"75034\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43947",
            "2",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "21210",
            "1",
            "42",
            "399",
            "16104",
            "116445",
            "368419",
            "75024",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-05",
            "12500.0000",
            "2.2900",
            "28625.00",
            "2.2900",
            "28625.00",
            "28625.00"
          ],
          "rowNumber": 1825786,
          "rowPosition": 1825787,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75024\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825787\" violates the foreign key: for \"id_contrato\": values \"75024\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "21",
            "1831096",
            "92",
            "1",
            "1",
            "501",
            "29932",
            "1",
            "51",
            "384",
            "14882",
            "92447",
            "368445",
            "75029",
            "889",
            "1831520",
            "2670",
            "2631",
            "2022",
            "2022-05-05",
            "0.0000",
            "71040.0000",
            "71040.00",
            "65899.9200",
            "65899.92",
            "65899.92"
          ],
          "rowNumber": 1826001,
          "rowPosition": 1826002,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75029\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826002\" violates the foreign key: for \"id_contrato\": values \"75029\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43982",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "825",
            "67465",
            "1",
            "8",
            "687",
            "14824",
            "91236",
            "368424",
            "75052",
            "889",
            "1831348",
            "2970",
            "2633",
            "2022",
            "2022-05-05",
            "0.0000",
            "58740.0000",
            "58740.00",
            "58000.0000",
            "58000.00",
            "58000.00"
          ],
          "rowNumber": 1826007,
          "rowPosition": 1826008,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75052\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826008\" violates the foreign key: for \"id_contrato\": values \"75052\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "58",
            "732",
            "21805",
            "183580",
            "368355",
            "75030",
            "1750",
            "1831373",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "12.0000",
            "807.2000",
            "9686.40",
            "807.2000",
            "9686.40",
            "9686.40"
          ],
          "rowNumber": 1827436,
          "rowPosition": 1827437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827437\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "58",
            "732",
            "21805",
            "183572",
            "368355",
            "75030",
            "1750",
            "1831373",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "2.0000",
            "1705.8500",
            "3411.70",
            "1705.8500",
            "3411.70",
            "3411.70"
          ],
          "rowNumber": 1827437,
          "rowPosition": 1827438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827438\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "58",
            "732",
            "21805",
            "183559",
            "368355",
            "75030",
            "1750",
            "1831373",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "18.0000",
            "595.9000",
            "10726.20",
            "595.9000",
            "10726.20",
            "10726.20"
          ],
          "rowNumber": 1827439,
          "rowPosition": 1827440,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827440\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "58",
            "732",
            "21805",
            "183557",
            "368355",
            "75030",
            "1750",
            "1831373",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "12.0000",
            "1309.8500",
            "15718.20",
            "1309.8500",
            "15718.20",
            "15718.20"
          ],
          "rowNumber": 1827440,
          "rowPosition": 1827441,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827441\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "32",
            "100",
            "11517",
            "147188",
            "368355",
            "75030",
            "903",
            "1831400",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "30.0000",
            "2167.1000",
            "65013.00",
            "2167.1000",
            "65013.00",
            "65013.00"
          ],
          "rowNumber": 1828090,
          "rowPosition": 1828091,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828091\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43945",
            "4",
            "1831071",
            "67",
            "1",
            "1",
            "66",
            "28556",
            "1",
            "51",
            "384",
            "14882",
            "130529",
            "368300",
            "75022",
            "889",
            "1831520",
            "2670",
            "3267",
            "2022",
            "2022-05-04",
            "0.0000",
            "115040.0000",
            "115040.00",
            "67800.2000",
            "67800.20",
            "67800.20"
          ],
          "rowNumber": 1828114,
          "rowPosition": 1828115,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75022\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828115\" violates the foreign key: for \"id_contrato\": values \"75022\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "4",
            "1831071",
            "67",
            "1",
            "1",
            "66",
            "56970",
            "1",
            "17",
            "379",
            "17564",
            "110037",
            "368225",
            "75041",
            "889",
            "1831449",
            "2594",
            "3267",
            "2022",
            "2022-05-03",
            "0.0000",
            "243142.5000",
            "243142.50",
            "66108.0000",
            "66108.00",
            "66108.00"
          ],
          "rowNumber": 1828200,
          "rowPosition": 1828201,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75041\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828201\" violates the foreign key: for \"id_contrato\": values \"75041\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "806",
            "56033",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "368285",
            "75032",
            "889",
            "1831731",
            "2879",
            "3043",
            "2022",
            "2022-05-03",
            "0.0000",
            "163742.2800",
            "163742.28",
            "147286.0700",
            "147286.07",
            "147286.07"
          ],
          "rowNumber": 1828233,
          "rowPosition": 1828234,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75032\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828234\" violates the foreign key: for \"id_contrato\": values \"75032\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "14",
            "1831046",
            "43",
            "1",
            "1",
            "206",
            "60554",
            "1",
            "51",
            "374",
            "1935",
            "93499",
            "368244",
            "75028",
            "889",
            "1831362",
            "2545",
            "2696",
            "2022",
            "2022-05-03",
            "0.0000",
            "5040.0000",
            "5040.00",
            "4992.0000",
            "4992.00",
            "4992.00"
          ],
          "rowNumber": 1828234,
          "rowPosition": 1828235,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75028\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828235\" violates the foreign key: for \"id_contrato\": values \"75028\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43953",
            "4",
            "1831095",
            "96",
            "2",
            "1",
            "883",
            "56196",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "368265",
            "75042",
            "889",
            "1831498",
            "2670",
            "3293",
            "2022",
            "2022-05-03",
            "0.0000",
            "284992.0000",
            "284992.00",
            "228000.0000",
            "228000.00",
            "228000.00"
          ],
          "rowNumber": 1828235,
          "rowPosition": 1828236,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828236\" violates the foreign key: for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43953",
            "4",
            "1831095",
            "96",
            "2",
            "1",
            "883",
            "56196",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "368265",
            "75042",
            "889",
            "1831498",
            "2670",
            "3293",
            "2022",
            "2022-05-03",
            "0.0000",
            "165400.0000",
            "165400.00",
            "128000.0000",
            "128000.00",
            "128000.00"
          ],
          "rowNumber": 1828236,
          "rowPosition": 1828237,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828237\" violates the foreign key: for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43953",
            "4",
            "1831095",
            "96",
            "2",
            "1",
            "883",
            "56196",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "368265",
            "75042",
            "889",
            "1831498",
            "2670",
            "3293",
            "2022",
            "2022-05-03",
            "0.0000",
            "392224.0000",
            "392224.00",
            "274600.0000",
            "274600.00",
            "274600.00"
          ],
          "rowNumber": 1828237,
          "rowPosition": 1828238,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828238\" violates the foreign key: for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43953",
            "4",
            "1831095",
            "96",
            "2",
            "1",
            "883",
            "56196",
            "1",
            "51",
            "382",
            "9755",
            "92902",
            "368265",
            "75042",
            "889",
            "1831498",
            "2670",
            "3293",
            "2022",
            "2022-05-03",
            "0.0000",
            "544320.0000",
            "544320.00",
            "437191.0000",
            "437191.00",
            "437191.00"
          ],
          "rowNumber": 1828238,
          "rowPosition": 1828239,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828239\" violates the foreign key: for \"id_contrato\": values \"75042\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "42",
            "107",
            "8411",
            "111235",
            "368355",
            "75030",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-05-04",
            "1.0000",
            "2389.4000",
            "2389.40",
            "2389.4000",
            "2389.40",
            "2389.40"
          ],
          "rowNumber": 1828414,
          "rowPosition": 1828415,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828415\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43997",
            "14",
            "1831083",
            "82",
            "1",
            "1",
            "233",
            "1919",
            "1",
            "9",
            "576",
            "20262",
            "93257",
            "368305",
            "75033",
            "889",
            "1831693",
            "2736",
            "2083",
            "2022",
            "2022-05-04",
            "0.0000",
            "2460.0000",
            "2460.00",
            "1560.0000",
            "1560.00",
            "1560.00"
          ],
          "rowNumber": 1828443,
          "rowPosition": 1828444,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75033\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828444\" violates the foreign key: for \"id_contrato\": values \"75033\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48936",
            "5",
            "1831084",
            "81",
            "1",
            "1",
            "856",
            "20137",
            "1",
            "17",
            "175",
            "6976",
            "92592",
            "368369",
            "75045",
            "889",
            "1831350",
            "2613",
            "1859",
            "2021",
            "2022-05-04",
            "0.0000",
            "1995303.5700",
            "1995303.57",
            "1634673.5100",
            "1634673.51",
            "1634673.51"
          ],
          "rowNumber": 1828447,
          "rowPosition": 1828448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75045\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828448\" violates the foreign key: for \"id_contrato\": values \"75045\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "32",
            "100",
            "11517",
            "88563",
            "368355",
            "75030",
            "830",
            "1831400",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "1.0000",
            "1423.1300",
            "1423.13",
            "1423.1300",
            "1423.13",
            "1423.13"
          ],
          "rowNumber": 1828454,
          "rowPosition": 1828455,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828455\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "42",
            "399",
            "1757",
            "86846",
            "368355",
            "75030",
            "890",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "32.0000",
            "4908.5000",
            "157072.00",
            "4908.5000",
            "157072.00",
            "157072.00"
          ],
          "rowNumber": 1828458,
          "rowPosition": 1828459,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828459\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "66212",
            "1",
            "32",
            "100",
            "11517",
            "86844",
            "368355",
            "75030",
            "900",
            "1831400",
            "2923",
            "3043",
            "2022",
            "2022-05-04",
            "7.0000",
            "1404.9000",
            "9834.30",
            "1404.9000",
            "9834.30",
            "9834.30"
          ],
          "rowNumber": 1828459,
          "rowPosition": 1828460,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828460\" violates the foreign key: for \"id_contrato\": values \"75030\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "19572",
            "1",
            "13",
            "199",
            "15434",
            "230350",
            "367747",
            "75025",
            "889",
            "1831958",
            "3019",
            "2633",
            "2022",
            "2022-04-26",
            "50.0000",
            "93366.0000",
            "4668300.00",
            "88000.0000",
            "4400000.00",
            "4400000.00"
          ],
          "rowNumber": 1828627,
          "rowPosition": 1828628,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75025\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828628\" violates the foreign key: for \"id_contrato\": values \"75025\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "21226",
            "1",
            "13",
            "110",
            "13000",
            "170396",
            "367747",
            "75023",
            "889",
            "1831958",
            "3019",
            "2633",
            "2022",
            "2022-04-26",
            "50.0000",
            "221322.8600",
            "11066143.00",
            "209000.0000",
            "10450000.00",
            "10450000.00"
          ],
          "rowNumber": 1828628,
          "rowPosition": 1828629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75023\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828629\" violates the foreign key: for \"id_contrato\": values \"75023\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "18049",
            "1",
            "60",
            "326",
            "19276",
            "182060",
            "367771",
            "75051",
            "889",
            "1831952",
            "2742",
            "3043",
            "2022",
            "2022-04-26",
            "15.0000",
            "7200.0000",
            "108000.00",
            "7200.0000",
            "108000.00",
            "108000.00"
          ],
          "rowNumber": 1829152,
          "rowPosition": 1829153,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75051\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829153\" violates the foreign key: for \"id_contrato\": values \"75051\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "60455",
            "1",
            "60",
            "326",
            "983",
            "274253",
            "367716",
            "75049",
            "889",
            "1831952",
            "2742",
            "3043",
            "2022",
            "2022-04-26",
            "64.0000",
            "2439.2700",
            "156113.28",
            "2439.2700",
            "156113.28",
            "156113.28"
          ],
          "rowNumber": 1829153,
          "rowPosition": 1829154,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75049\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829154\" violates the foreign key: for \"id_contrato\": values \"75049\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49893",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "17936",
            "1",
            "42",
            "104",
            "22561",
            "303082",
            "367618",
            "75036",
            "1729",
            "1831334",
            "2813",
            "2081",
            "2021",
            "2022-04-20",
            "2.0000",
            "981300.0000",
            "1962600.00",
            "703150.0000",
            "1406300.00",
            "1406300.00"
          ],
          "rowNumber": 1829725,
          "rowPosition": 1829726,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75036\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829726\" violates the foreign key: for \"id_contrato\": values \"75036\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43942",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "14052",
            "1",
            "63",
            "121",
            "5644",
            "151425",
            "367928",
            "75047",
            "889",
            "1831975",
            "2658",
            "1760",
            "2022",
            "2022-04-28",
            "2.0000",
            "213.3300",
            "426.66",
            "213.0000",
            "426.00",
            "426.00"
          ],
          "rowNumber": 1830169,
          "rowPosition": 1830170,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830170\" violates the foreign key: for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43942",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "14052",
            "1",
            "63",
            "121",
            "5644",
            "154289",
            "367928",
            "75047",
            "889",
            "1831975",
            "2658",
            "1760",
            "2022",
            "2022-04-28",
            "2.0000",
            "283.3300",
            "566.66",
            "283.0000",
            "566.00",
            "566.00"
          ],
          "rowNumber": 1830170,
          "rowPosition": 1830171,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830171\" violates the foreign key: for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43942",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "14052",
            "1",
            "63",
            "121",
            "5644",
            "154280",
            "367928",
            "75047",
            "889",
            "1831975",
            "2658",
            "1760",
            "2022",
            "2022-04-28",
            "1.0000",
            "1216.6700",
            "1216.67",
            "1216.0000",
            "1216.00",
            "1216.00"
          ],
          "rowNumber": 1830171,
          "rowPosition": 1830172,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830172\" violates the foreign key: for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43942",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "14052",
            "1",
            "63",
            "121",
            "5644",
            "157694",
            "367928",
            "75047",
            "889",
            "1831975",
            "2658",
            "1760",
            "2022",
            "2022-04-28",
            "246.0000",
            "36.6700",
            "9020.82",
            "36.0000",
            "8856.00",
            "8856.00"
          ],
          "rowNumber": 1830173,
          "rowPosition": 1830174,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830174\" violates the foreign key: for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43942",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "14052",
            "1",
            "63",
            "121",
            "5644",
            "157696",
            "367928",
            "75047",
            "889",
            "1831975",
            "2658",
            "1760",
            "2022",
            "2022-04-28",
            "228.0000",
            "48.3300",
            "11019.24",
            "47.7300",
            "10882.44",
            "10882.44"
          ],
          "rowNumber": 1830174,
          "rowPosition": 1830175,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830175\" violates the foreign key: for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43942",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "14052",
            "1",
            "63",
            "121",
            "5644",
            "260890",
            "367928",
            "75047",
            "889",
            "1831975",
            "2658",
            "1760",
            "2022",
            "2022-04-28",
            "6.0000",
            "57.6700",
            "346.02",
            "57.0000",
            "342.00",
            "342.00"
          ],
          "rowNumber": 1830175,
          "rowPosition": 1830176,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830176\" violates the foreign key: for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43942",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "14052",
            "1",
            "63",
            "121",
            "5644",
            "151427",
            "367928",
            "75047",
            "889",
            "1831975",
            "2658",
            "1760",
            "2022",
            "2022-04-28",
            "7.0000",
            "173.3300",
            "1213.31",
            "173.0000",
            "1211.00",
            "1211.00"
          ],
          "rowNumber": 1830176,
          "rowPosition": 1830177,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830177\" violates the foreign key: for \"id_contrato\": values \"75047\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50366",
            "1",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "21074",
            "1",
            "32",
            "236",
            "22153",
            "226928",
            "367922",
            "75026",
            "1913",
            "1831400",
            "2796",
            "2842",
            "2022",
            "2022-04-28",
            "87.0000",
            "18430.5400",
            "1603456.98",
            "18430.5400",
            "1603456.98",
            "1603456.98"
          ],
          "rowNumber": 1830858,
          "rowPosition": 1830859,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75026\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830859\" violates the foreign key: for \"id_contrato\": values \"75026\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44003",
            "2",
            "1831044",
            "36",
            "1",
            "1",
            "246",
            "71030",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "368526",
            "75046",
            "322",
            "1831697",
            "2932",
            "2633",
            "2022",
            "2022-05-06",
            "0.0000",
            "12000.0000",
            "12000.00",
            "12000.0000",
            "12000.00",
            "12000.00"
          ],
          "rowNumber": 1830976,
          "rowPosition": 1830977,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75046\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830977\" violates the foreign key: for \"id_contrato\": values \"75046\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49843",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "16497",
            "172630",
            "367978",
            "75050",
            "889",
            "1831373",
            "2813",
            "3331",
            "2021",
            "2022-04-28",
            "2.0000",
            "24300.0000",
            "48600.00",
            "24300.0000",
            "48600.00",
            "48600.00"
          ],
          "rowNumber": 1831171,
          "rowPosition": 1831172,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75050\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831172\" violates the foreign key: for \"id_contrato\": values \"75050\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49843",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "16497",
            "149069",
            "367978",
            "75050",
            "889",
            "1831373",
            "2813",
            "3331",
            "2021",
            "2022-04-28",
            "1.0000",
            "30000.0000",
            "30000.00",
            "23128.0000",
            "23128.00",
            "23128.00"
          ],
          "rowNumber": 1831172,
          "rowPosition": 1831173,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75050\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831173\" violates the foreign key: for \"id_contrato\": values \"75050\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50366",
            "1",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "21074",
            "1",
            "32",
            "236",
            "22153",
            "226928",
            "367936",
            "75026",
            "1913",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2022-04-28",
            "87.0000",
            "18430.5400",
            "1603456.98",
            "18430.5400",
            "1603456.98",
            "1603456.98"
          ],
          "rowNumber": 1831516,
          "rowPosition": 1831517,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75026\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831517\" violates the foreign key: for \"id_contrato\": values \"75026\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49843",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "63240",
            "1",
            "58",
            "411",
            "5752",
            "242100",
            "367978",
            "75054",
            "889",
            "1831373",
            "2813",
            "3331",
            "2021",
            "2022-04-28",
            "1.0000",
            "64840.4000",
            "64840.40",
            "49000.0000",
            "49000.00",
            "49000.00"
          ],
          "rowNumber": 1831517,
          "rowPosition": 1831518,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75054\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831518\" violates the foreign key: for \"id_contrato\": values \"75054\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49843",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "63240",
            "1",
            "58",
            "411",
            "5752",
            "144841",
            "367978",
            "75054",
            "889",
            "1831373",
            "2813",
            "3331",
            "2021",
            "2022-04-28",
            "1.0000",
            "149246.0000",
            "149246.00",
            "141000.0000",
            "141000.00",
            "141000.00"
          ],
          "rowNumber": 1831518,
          "rowPosition": 1831519,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75054\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831519\" violates the foreign key: for \"id_contrato\": values \"75054\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 124
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 124,
    "tasks": 1
  },
  "valid": false
}