{
  "version": "4.28.0",
  "time": 145.969,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp",
        "title": "Diárias SCDP",
        "path": "data/ft_diarias_scdp.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_favorecido",
              "title": "Favorecido - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_cargo",
              "title": "Cargo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao_scdp",
              "title": "Funçao - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao",
              "title": "Órgão- Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_pais_origem",
              "title": "Pais Origem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_estado_origem",
              "title": "Estado Origem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_cidade_origem",
              "title": "Cidade Origem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_pais_destino",
              "title": "Pais Destino - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_estado_destino",
              "title": "Estado Destino - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_cidade_destino",
              "title": "Cidade Destino - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem- Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_viagem",
              "title": "Tipo de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_viajante",
              "title": "Tipo de Viajante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_meio_transporte",
              "title": "Meio de Transporte - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_motivo",
              "title": "Motivo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "ordem_trecho",
              "title": "Ordem do Trecho",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n Ordem sequencial dos trechos da viagem constante na PCDP (Proposta de Concessão de Diárias e Passagensno) \n do Sistema de Concessão Diárias e Passagens (SCDP).\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_inicio_trecho",
              "title": "Data início do trecho",
              "type": "date",
              "format": "default",
              "description": "Data de ínicio da viagem correspondete ao trecho.\n"
            },
            {
              "name": "dt_fim_trecho",
              "title": "Data fim do trecho",
              "type": "date",
              "format": "default",
              "description": "Data fim da viagem correspondete ao trecho.\n"
            },
            {
              "name": "qt_diaria",
              "title": "Quantidade de diárias",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Quantidade de diárias pagas pelo órgão em razão das viagens a trabalho. \n",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_diaria",
              "title": "Valor da diária",
              "type": "number",
              "format": "default",
              "decimalChar": ".",
              "bareNumber": true,
              "description": "- > \n  Valor total pago pelo órgão ao servidor público ou colaborador eventual para custear suas despesas com alimentação,\n  estadia e deslocamento durante a viagem a trabalho. \n\n  Os valores unitários das diárias consta no [Decreto nº 47.045/16](https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=dec&num=47045&ano=2016).\n",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_passagem",
              "title": "Valor da Passagem",
              "type": "number",
              "format": "default",
              "decimalChar": ".",
              "bareNumber": true,
              "description": "Valor total pago referente às despesas com passagens aéreas e terrestres de servidor público ou colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_cargo"
              ],
              "reference": {
                "fields": [
                  "id_cargo"
                ],
                "resource": "dm_cargo_scdp"
              }
            },
            {
              "fields": [
                "id_pais_origem"
              ],
              "reference": {
                "fields": [
                  "id_pais"
                ],
                "resource": "dm_pais"
              }
            },
            {
              "fields": [
                "id_estado_origem"
              ],
              "reference": {
                "fields": [
                  "id_estado"
                ],
                "resource": "dm_estado"
              }
            },
            {
              "fields": [
                "id_funcao_scdp"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_scdp"
              }
            },
            {
              "fields": [
                "id_pais_destino"
              ],
              "reference": {
                "fields": [
                  "id_pais"
                ],
                "resource": "dm_pais"
              }
            },
            {
              "fields": [
                "id_cidade_destino"
              ],
              "reference": {
                "fields": [
                  "id_cidade"
                ],
                "resource": "dm_cidade"
              }
            },
            {
              "fields": [
                "id_favorecido"
              ],
              "reference": {
                "fields": [
                  "id_favorecido"
                ],
                "resource": "dm_favorecido_scdp"
              }
            },
            {
              "fields": [
                "id_estado_destino"
              ],
              "reference": {
                "fields": [
                  "id_estado"
                ],
                "resource": "dm_estado"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_tipo_viagem"
              ],
              "reference": {
                "fields": [
                  "id_tipo_viagem"
                ],
                "resource": "dm_tipo_viagem"
              }
            },
            {
              "fields": [
                "id_orgao"
              ],
              "reference": {
                "fields": [
                  "id_orgao"
                ],
                "resource": "dm_orgao_scdp"
              }
            },
            {
              "fields": [
                "id_meio_transporte"
              ],
              "reference": {
                "fields": [
                  "id_meio_transporte"
                ],
                "resource": "dm_meio_transporte"
              }
            },
            {
              "fields": [
                "id_motivo"
              ],
              "reference": {
                "fields": [
                  "id_motivo"
                ],
                "resource": "dm_motivo_viagem"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_tipo_viajante"
              ],
              "reference": {
                "fields": [
                  "id_tipo_viajante"
                ],
                "resource": "dm_tipo_viajante"
              }
            },
            {
              "fields": [
                "id_cidade_origem"
              ],
              "reference": {
                "fields": [
                  "id_cidade"
                ],
                "resource": "dm_cidade"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "19f32148bfe573429906cc677f4677a5",
          "bytes": 16851869,
          "fields": 23,
          "rows": 1255617
        }
      },
      "time": 145.969,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "47610",
            "48991",
            "1",
            "1",
            "44",
            "1",
            "12",
            "4827",
            "1",
            "12",
            "5595",
            "573088",
            "1",
            "25",
            "5",
            "441",
            "1",
            "2019",
            "2019-12-19",
            "2019-12-21",
            "2.00",
            "546.00",
            "0.00"
          ],
          "rowNumber": 943252,
          "rowPosition": 943253,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943253\" violates the foreign key: for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "47610",
            "48991",
            "1",
            "1",
            "44",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "4827",
            "573088",
            "1",
            "25",
            "5",
            "441",
            "2",
            "2019",
            "2019-12-21",
            "2019-12-21",
            "0.35",
            "95.55",
            "0.00"
          ],
          "rowNumber": 943253,
          "rowPosition": 943254,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943254\" violates the foreign key: for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50338",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573099",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-01-28",
            "2022-01-28",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 943260,
          "rowPosition": 943261,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943261\" violates the foreign key: for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50338",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573099",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-01-27",
            "2022-01-28",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 943261,
          "rowPosition": 943262,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943262\" violates the foreign key: for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50341",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573100",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-01-30",
            "2022-01-30",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 943270,
          "rowPosition": 943271,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943271\" violates the foreign key: for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50341",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573100",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-01-30",
            "2022-01-30",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 943271,
          "rowPosition": 943272,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943272\" violates the foreign key: for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50345",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573101",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-02-04",
            "2022-02-04",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 943280,
          "rowPosition": 943281,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943281\" violates the foreign key: for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50345",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573101",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-02-03",
            "2022-02-04",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 943281,
          "rowPosition": 943282,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943282\" violates the foreign key: for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50347",
            "36544",
            "75",
            "5220",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573109",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-02-05",
            "2022-02-05",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 943284,
          "rowPosition": 943285,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943285\" violates the foreign key: for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50347",
            "36544",
            "75",
            "5220",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573109",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-02-05",
            "2022-02-05",
            "0.50",
            "211.40",
            "0.00"
          ],
          "rowNumber": 943285,
          "rowPosition": 943286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943286\" violates the foreign key: for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50352",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573102",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-02-11",
            "2022-02-11",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 943286,
          "rowPosition": 943287,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943287\" violates the foreign key: for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50352",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573102",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-02-10",
            "2022-02-11",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 943287,
          "rowPosition": 943288,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"943288\" violates the foreign key: for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50354",
            "36544",
            "75",
            "5220",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573110",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-02-13",
            "2022-02-13",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 944429,
          "rowPosition": 944430,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944430\" violates the foreign key: for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50354",
            "36544",
            "75",
            "5220",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573110",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-02-12",
            "2022-02-13",
            "0.50",
            "211.40",
            "0.00"
          ],
          "rowNumber": 944430,
          "rowPosition": 944431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944431\" violates the foreign key: for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43941",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573105",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-03-04",
            "2022-03-04",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 944431,
          "rowPosition": 944432,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944432\" violates the foreign key: for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43941",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573105",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-03-03",
            "2022-03-04",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 944432,
          "rowPosition": 944433,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944433\" violates the foreign key: for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43943",
            "40446",
            "30",
            "314",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573098",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-03-05",
            "2022-03-05",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 944435,
          "rowPosition": 944436,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944436\" violates the foreign key: for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43943",
            "40446",
            "30",
            "314",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573098",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-03-05",
            "2022-03-05",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 944436,
          "rowPosition": 944437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944437\" violates the foreign key: for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50357",
            "5498",
            "52",
            "4668",
            "32",
            "1",
            "12",
            "4959",
            "1",
            "12",
            "5614",
            "573089",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-02-16",
            "2022-02-16",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 944441,
          "rowPosition": 944442,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944442\" violates the foreign key: for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50357",
            "5498",
            "52",
            "4668",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "4959",
            "573089",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-02-15",
            "2022-02-16",
            "1.00",
            "210.00",
            "0.00"
          ],
          "rowNumber": 944442,
          "rowPosition": 944443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944443\" violates the foreign key: for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50359",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573103",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-02-18",
            "2022-02-18",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 944464,
          "rowPosition": 944465,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944465\" violates the foreign key: for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50359",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573103",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-02-17",
            "2022-02-18",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 944465,
          "rowPosition": 944466,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944466\" violates the foreign key: for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50362",
            "36544",
            "75",
            "5220",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573111",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-02-20",
            "2022-02-20",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 944466,
          "rowPosition": 944467,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944467\" violates the foreign key: for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50362",
            "36544",
            "75",
            "5220",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573111",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-02-20",
            "2022-02-20",
            "0.50",
            "211.40",
            "0.00"
          ],
          "rowNumber": 944467,
          "rowPosition": 944468,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944468\" violates the foreign key: for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50366",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573104",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-02-25",
            "2022-02-25",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 944480,
          "rowPosition": 944481,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944481\" violates the foreign key: for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50366",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573104",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-02-24",
            "2022-02-25",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 944481,
          "rowPosition": 944482,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"944482\" violates the foreign key: for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573106",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-03-11",
            "2022-03-11",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248784,
          "rowPosition": 1248785,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248785\" violates the foreign key: for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573106",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-03-10",
            "2022-03-11",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 1248785,
          "rowPosition": 1248786,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248786\" violates the foreign key: for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "10987",
            "73",
            "5319",
            "47",
            "1",
            "12",
            "5063",
            "1",
            "12",
            "5176",
            "573116",
            "1",
            "1",
            "7",
            "16",
            "2",
            "2022",
            "2022-03-11",
            "2022-03-11",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248786,
          "rowPosition": 1248787,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248787\" violates the foreign key: for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "10987",
            "73",
            "5319",
            "47",
            "1",
            "12",
            "5176",
            "1",
            "12",
            "5063",
            "573116",
            "1",
            "1",
            "7",
            "16",
            "1",
            "2022",
            "2022-03-11",
            "2022-03-11",
            "0.50",
            "144.72",
            "0.00"
          ],
          "rowNumber": 1248787,
          "rowPosition": 1248788,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248788\" violates the foreign key: for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43953",
            "10481",
            "75",
            "5202",
            "47",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "5300",
            "573113",
            "1",
            "1",
            "7",
            "566",
            "2",
            "2022",
            "2022-03-17",
            "2022-03-17",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248798,
          "rowPosition": 1248799,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248799\" violates the foreign key: for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43953",
            "10481",
            "75",
            "5202",
            "47",
            "1",
            "12",
            "5300",
            "1",
            "12",
            "5595",
            "573113",
            "1",
            "1",
            "7",
            "566",
            "1",
            "2022",
            "2022-03-15",
            "2022-03-17",
            "2.00",
            "1619.70",
            "0.00"
          ],
          "rowNumber": 1248799,
          "rowPosition": 1248800,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248800\" violates the foreign key: for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "49862",
            "30",
            "314",
            "47",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "5176",
            "573119",
            "1",
            "1",
            "7",
            "16",
            "2",
            "2022",
            "2022-03-17",
            "2022-03-17",
            "0.50",
            "136.50",
            "0.00"
          ],
          "rowNumber": 1248802,
          "rowPosition": 1248803,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248803\" violates the foreign key: for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "49862",
            "30",
            "314",
            "47",
            "1",
            "12",
            "5176",
            "1",
            "12",
            "5595",
            "573119",
            "1",
            "1",
            "7",
            "16",
            "1",
            "2022",
            "2022-03-16",
            "2022-03-17",
            "1.00",
            "273.00",
            "0.00"
          ],
          "rowNumber": 1248803,
          "rowPosition": 1248804,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248804\" violates the foreign key: for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "54003",
            "30",
            "314",
            "47",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "5176",
            "573118",
            "1",
            "1",
            "7",
            "16",
            "2",
            "2022",
            "2022-03-17",
            "2022-03-17",
            "0.50",
            "136.50",
            "0.00"
          ],
          "rowNumber": 1248804,
          "rowPosition": 1248805,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248805\" violates the foreign key: for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43954",
            "54003",
            "30",
            "314",
            "47",
            "1",
            "12",
            "5176",
            "1",
            "12",
            "5595",
            "573118",
            "1",
            "1",
            "7",
            "16",
            "1",
            "2022",
            "2022-03-16",
            "2022-03-17",
            "1.00",
            "273.00",
            "0.00"
          ],
          "rowNumber": 1248805,
          "rowPosition": 1248806,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248806\" violates the foreign key: for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5529",
            "573107",
            "1",
            "1",
            "7",
            "15",
            "2",
            "2022",
            "2022-03-18",
            "2022-03-18",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248806,
          "rowPosition": 1248807,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248807\" violates the foreign key: for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "54458",
            "136",
            "4495",
            "47",
            "1",
            "12",
            "5529",
            "1",
            "12",
            "5582",
            "573107",
            "1",
            "1",
            "7",
            "15",
            "1",
            "2022",
            "2022-03-17",
            "2022-03-18",
            "0.50",
            "79.06",
            "0.00"
          ],
          "rowNumber": 1248807,
          "rowPosition": 1248808,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248808\" violates the foreign key: for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "59180",
            "235",
            "5330",
            "47",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "5595",
            "573112",
            "1",
            "1",
            "0",
            "566",
            "2",
            "2022",
            "2022-03-18",
            "2022-03-19",
            "0.50",
            "233.07",
            "0.00"
          ],
          "rowNumber": 1248808,
          "rowPosition": 1248809,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248809\" violates the foreign key: for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "59180",
            "235",
            "5330",
            "47",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "5582",
            "573112",
            "1",
            "1",
            "7",
            "566",
            "3",
            "2022",
            "2022-03-19",
            "2022-03-19",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248809,
          "rowPosition": 1248810,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248810\" violates the foreign key: for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "59180",
            "235",
            "5330",
            "47",
            "1",
            "12",
            "5582",
            "1",
            "12",
            "5595",
            "573112",
            "1",
            "1",
            "7",
            "566",
            "1",
            "2022",
            "2022-03-17",
            "2022-03-18",
            "1.00",
            "466.13",
            "0.00"
          ],
          "rowNumber": 1248810,
          "rowPosition": 1248811,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248811\" violates the foreign key: for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "10987",
            "73",
            "5319",
            "47",
            "1",
            "12",
            "5063",
            "1",
            "12",
            "5176",
            "573117",
            "1",
            "1",
            "7",
            "16",
            "2",
            "2022",
            "2022-03-18",
            "2022-03-18",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248811,
          "rowPosition": 1248812,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248812\" violates the foreign key: for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "10987",
            "73",
            "5319",
            "47",
            "1",
            "12",
            "5176",
            "1",
            "12",
            "5063",
            "573117",
            "1",
            "1",
            "7",
            "16",
            "1",
            "2022",
            "2022-03-18",
            "2022-03-18",
            "0.50",
            "144.72",
            "0.00"
          ],
          "rowNumber": 1248812,
          "rowPosition": 1248813,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248813\" violates the foreign key: for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43965",
            "5960",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "5614",
            "573097",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-02",
            "2022-04-02",
            "0.35",
            "133.70",
            "0.00"
          ],
          "rowNumber": 1248822,
          "rowPosition": 1248823,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248823\" violates the foreign key: for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43965",
            "5960",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "5595",
            "573097",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-03-27",
            "2022-04-02",
            "6.00",
            "2292.00",
            "0.00"
          ],
          "rowNumber": 1248823,
          "rowPosition": 1248824,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248824\" violates the foreign key: for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "389",
            "32",
            "3646",
            "50",
            "1",
            "12",
            "5601",
            "1",
            "12",
            "5615",
            "573095",
            "1",
            "1",
            "7",
            "182",
            "3",
            "2022",
            "2022-03-30",
            "2022-03-31",
            "1.00",
            "260.91",
            "0.00"
          ],
          "rowNumber": 1248830,
          "rowPosition": 1248831,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248831\" violates the foreign key: for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "389",
            "32",
            "3646",
            "50",
            "1",
            "12",
            "5421",
            "1",
            "12",
            "5601",
            "573095",
            "1",
            "1",
            "7",
            "182",
            "2",
            "2022",
            "2022-03-29",
            "2022-03-30",
            "1.00",
            "260.91",
            "0.00"
          ],
          "rowNumber": 1248831,
          "rowPosition": 1248832,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248832\" violates the foreign key: for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "389",
            "32",
            "3646",
            "50",
            "1",
            "12",
            "5480",
            "1",
            "12",
            "5597",
            "573095",
            "1",
            "1",
            "7",
            "182",
            "5",
            "2022",
            "2022-04-01",
            "2022-04-01",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248832,
          "rowPosition": 1248833,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248833\" violates the foreign key: for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "1878",
            "112",
            "3646",
            "50",
            "1",
            "12",
            "5601",
            "1",
            "12",
            "5615",
            "573096",
            "1",
            "1",
            "7",
            "118",
            "3",
            "2022",
            "2022-03-30",
            "2022-03-31",
            "1.00",
            "260.91",
            "0.00"
          ],
          "rowNumber": 1248833,
          "rowPosition": 1248834,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248834\" violates the foreign key: for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "1878",
            "112",
            "3646",
            "50",
            "1",
            "12",
            "5421",
            "1",
            "12",
            "5601",
            "573096",
            "1",
            "1",
            "7",
            "118",
            "2",
            "2022",
            "2022-03-29",
            "2022-03-30",
            "1.00",
            "260.91",
            "0.00"
          ],
          "rowNumber": 1248834,
          "rowPosition": 1248835,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248835\" violates the foreign key: for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "1878",
            "112",
            "3646",
            "50",
            "1",
            "12",
            "5480",
            "1",
            "12",
            "5597",
            "573096",
            "1",
            "1",
            "7",
            "118",
            "5",
            "2022",
            "2022-04-01",
            "2022-04-01",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248835,
          "rowPosition": 1248836,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248836\" violates the foreign key: for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "4886",
            "1",
            "12",
            "5615",
            "573136",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-03-28",
            "2022-03-28",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248837,
          "rowPosition": 1248838,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248838\" violates the foreign key: for \"id_documento_viagem\": values \"573136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43966",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5615",
            "1",
            "12",
            "4886",
            "573136",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-03-28",
            "2022-03-28",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1248838,
          "rowPosition": 1248839,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1248839\" violates the foreign key: for \"id_documento_viagem\": values \"573136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "42020",
            "52",
            "4668",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "20",
            "15",
            "573122",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-03-31",
            "2022-03-31",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249161,
          "rowPosition": 1249162,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249162\" violates the foreign key: for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "42020",
            "52",
            "4668",
            "32",
            "1",
            "20",
            "15",
            "1",
            "12",
            "5614",
            "573122",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-03-31",
            "2022-03-31",
            "0.35",
            "133.70",
            "0.00"
          ],
          "rowNumber": 1249162,
          "rowPosition": 1249163,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249163\" violates the foreign key: for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "58252",
            "1",
            "1",
            "44",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "5276",
            "573115",
            "1",
            "3",
            "5",
            "1",
            "2",
            "2022",
            "2022-03-31",
            "2022-03-31",
            "0.35",
            "133.70",
            "0.00"
          ],
          "rowNumber": 1249163,
          "rowPosition": 1249164,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249164\" violates the foreign key: for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "58252",
            "1",
            "1",
            "44",
            "1",
            "12",
            "5276",
            "1",
            "12",
            "5595",
            "573115",
            "1",
            "3",
            "5",
            "1",
            "1",
            "2022",
            "2022-03-31",
            "2022-03-31",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249164,
          "rowPosition": 1249165,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249165\" violates the foreign key: for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5361",
            "1",
            "12",
            "5615",
            "573137",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-01",
            "2022-04-01",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249165,
          "rowPosition": 1249166,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249166\" violates the foreign key: for \"id_documento_viagem\": values \"573137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5615",
            "1",
            "12",
            "5361",
            "573137",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-01",
            "2022-04-01",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249166,
          "rowPosition": 1249167,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249167\" violates the foreign key: for \"id_documento_viagem\": values \"573137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "59160",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5361",
            "1",
            "12",
            "5615",
            "573123",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-01",
            "2022-04-01",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249167,
          "rowPosition": 1249168,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573123\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249168\" violates the foreign key: for \"id_documento_viagem\": values \"573123\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "59160",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5615",
            "1",
            "12",
            "5361",
            "573123",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-01",
            "2022-04-01",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249168,
          "rowPosition": 1249169,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573123\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249169\" violates the foreign key: for \"id_documento_viagem\": values \"573123\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "5221",
            "174",
            "3575",
            "32",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5614",
            "573108",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-08",
            "2022-04-08",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249172,
          "rowPosition": 1249173,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249173\" violates the foreign key: for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "5221",
            "174",
            "3575",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "4900",
            "573108",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-04",
            "2022-04-08",
            "4.00",
            "840.00",
            "0.00"
          ],
          "rowNumber": 1249173,
          "rowPosition": 1249174,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249174\" violates the foreign key: for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "7133",
            "111",
            "273",
            "50",
            "1",
            "12",
            "4937",
            "1",
            "12",
            "5595",
            "573114",
            "1",
            "1",
            "7",
            "179",
            "2",
            "2022",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249174,
          "rowPosition": 1249175,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249175\" violates the foreign key: for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "7133",
            "111",
            "273",
            "50",
            "1",
            "12",
            "5595",
            "1",
            "12",
            "4937",
            "573114",
            "1",
            "1",
            "7",
            "179",
            "1",
            "2022",
            "2022-04-04",
            "2022-04-08",
            "4.00",
            "840.00",
            "0.00"
          ],
          "rowNumber": 1249175,
          "rowPosition": 1249176,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249176\" violates the foreign key: for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43974",
            "3052",
            "37",
            "89",
            "24",
            "1",
            "8",
            "16",
            "1",
            "12",
            "5595",
            "573121",
            "1",
            "1",
            "1",
            "1",
            "2",
            "2022",
            "2022-04-07",
            "2022-04-07",
            "0.35",
            "133.70",
            "947.23"
          ],
          "rowNumber": 1249184,
          "rowPosition": 1249185,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249185\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43974",
            "3052",
            "37",
            "89",
            "24",
            "1",
            "12",
            "5595",
            "1",
            "8",
            "16",
            "573121",
            "1",
            "1",
            "1",
            "1",
            "1",
            "2022",
            "2022-04-05",
            "2022-04-07",
            "2.00",
            "764.00",
            "971.90"
          ],
          "rowNumber": 1249185,
          "rowPosition": 1249186,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249186\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "6403",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5056",
            "1",
            "12",
            "5614",
            "573092",
            "1",
            "26",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-08",
            "2022-04-08",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249186,
          "rowPosition": 1249187,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249187\" violates the foreign key: for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "6403",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "5056",
            "573092",
            "1",
            "26",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-08",
            "2.00",
            "420.00",
            "0.00"
          ],
          "rowNumber": 1249187,
          "rowPosition": 1249188,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249188\" violates the foreign key: for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "6406",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5056",
            "1",
            "12",
            "5614",
            "573091",
            "1",
            "26",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-08",
            "2022-04-08",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249188,
          "rowPosition": 1249189,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249189\" violates the foreign key: for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "6406",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "5056",
            "573091",
            "1",
            "26",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-08",
            "2.00",
            "420.00",
            "0.00"
          ],
          "rowNumber": 1249189,
          "rowPosition": 1249190,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249190\" violates the foreign key: for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5149",
            "1",
            "12",
            "5615",
            "573138",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249190,
          "rowPosition": 1249191,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249191\" violates the foreign key: for \"id_documento_viagem\": values \"573138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5615",
            "1",
            "12",
            "5149",
            "573138",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249191,
          "rowPosition": 1249192,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249192\" violates the foreign key: for \"id_documento_viagem\": values \"573138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12552",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573131",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249192,
          "rowPosition": 1249193,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249193\" violates the foreign key: for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12552",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573131",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249193,
          "rowPosition": 1249194,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249194\" violates the foreign key: for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12553",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573127",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249194,
          "rowPosition": 1249195,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249195\" violates the foreign key: for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12553",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573127",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249195,
          "rowPosition": 1249196,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249196\" violates the foreign key: for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12555",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573128",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249196,
          "rowPosition": 1249197,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249197\" violates the foreign key: for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12555",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573128",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249197,
          "rowPosition": 1249198,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249198\" violates the foreign key: for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12562",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573125",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249198,
          "rowPosition": 1249199,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249199\" violates the foreign key: for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "12562",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573125",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249199,
          "rowPosition": 1249200,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249200\" violates the foreign key: for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "13217",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573132",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249200,
          "rowPosition": 1249201,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249201\" violates the foreign key: for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "13217",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573132",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249201,
          "rowPosition": 1249202,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249202\" violates the foreign key: for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "49312",
            "52",
            "4668",
            "32",
            "1",
            "12",
            "5056",
            "1",
            "12",
            "5614",
            "573090",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-08",
            "2022-04-08",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249204,
          "rowPosition": 1249205,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249205\" violates the foreign key: for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "49312",
            "52",
            "4668",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "5056",
            "573090",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-08",
            "2.00",
            "420.00",
            "0.00"
          ],
          "rowNumber": 1249205,
          "rowPosition": 1249206,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249206\" violates the foreign key: for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "55254",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "5486",
            "573130",
            "1",
            "22",
            "6",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249206,
          "rowPosition": 1249207,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249207\" violates the foreign key: for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "55254",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5486",
            "1",
            "12",
            "5575",
            "573130",
            "1",
            "22",
            "6",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249207,
          "rowPosition": 1249208,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249208\" violates the foreign key: for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "55426",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573124",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249208,
          "rowPosition": 1249209,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249209\" violates the foreign key: for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "55426",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573124",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249209,
          "rowPosition": 1249210,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249210\" violates the foreign key: for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "55415",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573129",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249210,
          "rowPosition": 1249211,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249211\" violates the foreign key: for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "55415",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573129",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249211,
          "rowPosition": 1249212,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249212\" violates the foreign key: for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "56226",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573126",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249212,
          "rowPosition": 1249213,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249213\" violates the foreign key: for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "56226",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573126",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249213,
          "rowPosition": 1249214,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249214\" violates the foreign key: for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "56433",
            "1",
            "1",
            "11",
            "1",
            "12",
            "4900",
            "1",
            "12",
            "5575",
            "573133",
            "1",
            "22",
            "7",
            "36",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249214,
          "rowPosition": 1249215,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249215\" violates the foreign key: for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "56433",
            "1",
            "1",
            "11",
            "1",
            "12",
            "5575",
            "1",
            "12",
            "4900",
            "573133",
            "1",
            "22",
            "7",
            "36",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249215,
          "rowPosition": 1249216,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249216\" violates the foreign key: for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "59384",
            "14",
            "2488",
            "19",
            "1",
            "8",
            "16",
            "1",
            "12",
            "5412",
            "573135",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249216,
          "rowPosition": 1249217,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249217\" violates the foreign key: for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "59384",
            "14",
            "2488",
            "19",
            "1",
            "12",
            "5412",
            "1",
            "8",
            "16",
            "573135",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-06",
            "2022-04-06",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249217,
          "rowPosition": 1249218,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249218\" violates the foreign key: for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "1430",
            "15",
            "3795",
            "40",
            "1",
            "12",
            "5163",
            "1",
            "12",
            "5540",
            "573134",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249220,
          "rowPosition": 1249221,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249221\" violates the foreign key: for \"id_documento_viagem\": values \"573134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "3039",
            "44",
            "3086",
            "18",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "5536",
            "573120",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-13",
            "2022-04-13",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249221,
          "rowPosition": 1249222,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249222\" violates the foreign key: for \"id_documento_viagem\": values \"573120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "6403",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5151",
            "1",
            "12",
            "5614",
            "573094",
            "1",
            "26",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-12",
            "2022-04-12",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249222,
          "rowPosition": 1249223,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249223\" violates the foreign key: for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "6403",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "5151",
            "573094",
            "1",
            "26",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-11",
            "2022-04-12",
            "1.00",
            "210.00",
            "0.00"
          ],
          "rowNumber": 1249223,
          "rowPosition": 1249224,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249224\" violates the foreign key: for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "6406",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5151",
            "1",
            "12",
            "5614",
            "573093",
            "1",
            "26",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-12",
            "2022-04-12",
            "0.35",
            "73.50",
            "0.00"
          ],
          "rowNumber": 1249224,
          "rowPosition": 1249225,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249225\" violates the foreign key: for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "6406",
            "1",
            "1",
            "32",
            "1",
            "12",
            "5614",
            "1",
            "12",
            "5151",
            "573093",
            "1",
            "26",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-11",
            "2022-04-12",
            "1.00",
            "210.00",
            "0.00"
          ],
          "rowNumber": 1249225,
          "rowPosition": 1249226,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249226\" violates the foreign key: for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5421",
            "1",
            "12",
            "5615",
            "573139",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-11",
            "2022-04-11",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249226,
          "rowPosition": 1249227,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249227\" violates the foreign key: for \"id_documento_viagem\": values \"573139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43980",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5615",
            "1",
            "12",
            "5421",
            "573139",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-11",
            "2022-04-11",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249227,
          "rowPosition": 1249228,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249228\" violates the foreign key: for \"id_documento_viagem\": values \"573139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43981",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5043",
            "1",
            "12",
            "5615",
            "573140",
            "1",
            "1",
            "7",
            "1",
            "2",
            "2022",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249228,
          "rowPosition": 1249229,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249229\" violates the foreign key: for \"id_documento_viagem\": values \"573140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43981",
            "9699",
            "55",
            "21",
            "32",
            "1",
            "12",
            "5615",
            "1",
            "12",
            "5043",
            "573140",
            "1",
            "1",
            "7",
            "1",
            "1",
            "2022",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 1249229,
          "rowPosition": 1249230,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"1249230\" violates the foreign key: for \"id_documento_viagem\": values \"573140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 107
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 107,
    "tasks": 1
  },
  "valid": false
}