{
  "version": "4.28.0",
  "time": 54.11,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "4fbd997771486858520a5cce4ca607f6",
          "bytes": 8731495,
          "fields": 14,
          "rows": 567297
        }
      },
      "time": 54.11,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "573088",
            "13280390",
            "14407",
            "1958",
            "34",
            "2768",
            "56146",
            "0",
            "1",
            "2614",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "189.95"
          ],
          "rowNumber": 566349,
          "rowPosition": 566350,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566350\" violates the foreign key: for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573088",
            "13280390",
            "14407",
            "1958",
            "34",
            "2768",
            "56146",
            "0",
            "1",
            "2614",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "189.95"
          ],
          "rowNumber": 566349,
          "rowPosition": 566350,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566350\" violates the foreign key: for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573088",
            "12341788",
            "13981",
            "1882",
            "34",
            "2800",
            "54021",
            "0",
            "528",
            "54",
            "2019-12-26",
            "2020-01-24",
            "0.00",
            "641.55"
          ],
          "rowNumber": 566350,
          "rowPosition": 566351,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566351\" violates the foreign key: for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573088",
            "12341788",
            "13981",
            "1882",
            "34",
            "2800",
            "54021",
            "0",
            "528",
            "54",
            "2019-12-26",
            "2020-01-24",
            "0.00",
            "641.55"
          ],
          "rowNumber": 566350,
          "rowPosition": 566351,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566351\" violates the foreign key: for \"id_documento_viagem\": values \"573088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573116",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "59",
            "59",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "18.81"
          ],
          "rowNumber": 566351,
          "rowPosition": 566352,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566352\" violates the foreign key: for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573116",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "59",
            "59",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "18.81"
          ],
          "rowNumber": 566351,
          "rowPosition": 566352,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566352\" violates the foreign key: for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573116",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "51",
            "51",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "144.72"
          ],
          "rowNumber": 566352,
          "rowPosition": 566353,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566353\" violates the foreign key: for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573116",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "51",
            "51",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "144.72"
          ],
          "rowNumber": 566352,
          "rowPosition": 566353,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566353\" violates the foreign key: for \"id_documento_viagem\": values \"573116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573111",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "45",
            "60",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "51.37"
          ],
          "rowNumber": 566353,
          "rowPosition": 566354,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566354\" violates the foreign key: for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573111",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "45",
            "60",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "51.37"
          ],
          "rowNumber": 566353,
          "rowPosition": 566354,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566354\" violates the foreign key: for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573111",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "20",
            "37",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "211.40"
          ],
          "rowNumber": 566354,
          "rowPosition": 566355,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566355\" violates the foreign key: for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573111",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "20",
            "37",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "211.40"
          ],
          "rowNumber": 566354,
          "rowPosition": 566355,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566355\" violates the foreign key: for \"id_documento_viagem\": values \"573111\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573096",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "184",
            "762",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "100.32"
          ],
          "rowNumber": 566357,
          "rowPosition": 566358,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566358\" violates the foreign key: for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573096",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "184",
            "762",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "100.32"
          ],
          "rowNumber": 566357,
          "rowPosition": 566358,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566358\" violates the foreign key: for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573096",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "129",
            "555",
            "2022-03-22",
            "2022-03-22",
            "0.00",
            "711.00"
          ],
          "rowNumber": 566358,
          "rowPosition": 566359,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566359\" violates the foreign key: for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573096",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "129",
            "555",
            "2022-03-22",
            "2022-03-22",
            "0.00",
            "711.00"
          ],
          "rowNumber": 566358,
          "rowPosition": 566359,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566359\" violates the foreign key: for \"id_documento_viagem\": values \"573096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573131",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "287",
            "1558",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566359,
          "rowPosition": 566360,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566360\" violates the foreign key: for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573131",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "287",
            "1558",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566359,
          "rowPosition": 566360,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566360\" violates the foreign key: for \"id_documento_viagem\": values \"573131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573098",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "33",
            "48",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566361,
          "rowPosition": 566362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566362\" violates the foreign key: for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573098",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "33",
            "48",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566361,
          "rowPosition": 566362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566362\" violates the foreign key: for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573098",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "6",
            "22",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566362,
          "rowPosition": 566363,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566363\" violates the foreign key: for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573098",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "6",
            "22",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566362,
          "rowPosition": 566363,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566363\" violates the foreign key: for \"id_documento_viagem\": values \"573098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573100",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "35",
            "50",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566365,
          "rowPosition": 566366,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566366\" violates the foreign key: for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573100",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "35",
            "50",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566365,
          "rowPosition": 566366,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566366\" violates the foreign key: for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573100",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "9",
            "26",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566366,
          "rowPosition": 566367,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566367\" violates the foreign key: for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573100",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "9",
            "26",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566366,
          "rowPosition": 566367,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566367\" violates the foreign key: for \"id_documento_viagem\": values \"573100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573115",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "82",
            "2615",
            "2022-04-13",
            "2022-04-13",
            "0.00",
            "67.27"
          ],
          "rowNumber": 566367,
          "rowPosition": 566368,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566368\" violates the foreign key: for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573115",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "82",
            "2615",
            "2022-04-13",
            "2022-04-13",
            "0.00",
            "67.27"
          ],
          "rowNumber": 566367,
          "rowPosition": 566368,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566368\" violates the foreign key: for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573115",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "73",
            "1794",
            "2022-03-29",
            "2022-03-29",
            "382.00",
            "515.70"
          ],
          "rowNumber": 566368,
          "rowPosition": 566369,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566369\" violates the foreign key: for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573115",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "73",
            "1794",
            "2022-03-29",
            "2022-03-29",
            "382.00",
            "515.70"
          ],
          "rowNumber": 566368,
          "rowPosition": 566369,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566369\" violates the foreign key: for \"id_documento_viagem\": values \"573115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573102",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "37",
            "52",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566373,
          "rowPosition": 566374,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566374\" violates the foreign key: for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573102",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "37",
            "52",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566373,
          "rowPosition": 566374,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566374\" violates the foreign key: for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573102",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "11",
            "28",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566374,
          "rowPosition": 566375,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566375\" violates the foreign key: for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573102",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "11",
            "28",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566374,
          "rowPosition": 566375,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566375\" violates the foreign key: for \"id_documento_viagem\": values \"573102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573135",
            "13212811",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "35",
            "558",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566375,
          "rowPosition": 566376,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566376\" violates the foreign key: for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573135",
            "13212811",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "35",
            "558",
            "2022-04-06",
            "2022-04-06",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566375,
          "rowPosition": 566376,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566376\" violates the foreign key: for \"id_documento_viagem\": values \"573135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573133",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "289",
            "1560",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566376,
          "rowPosition": 566377,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566377\" violates the foreign key: for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573133",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "289",
            "1560",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566376,
          "rowPosition": 566377,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566377\" violates the foreign key: for \"id_documento_viagem\": values \"573133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573104",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "39",
            "54",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566377,
          "rowPosition": 566378,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566378\" violates the foreign key: for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573104",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "39",
            "54",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566377,
          "rowPosition": 566378,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566378\" violates the foreign key: for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573104",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "13",
            "30",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566378,
          "rowPosition": 566379,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566379\" violates the foreign key: for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573104",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "13",
            "30",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566378,
          "rowPosition": 566379,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566379\" violates the foreign key: for \"id_documento_viagem\": values \"573104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573132",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "288",
            "1559",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566381,
          "rowPosition": 566382,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566382\" violates the foreign key: for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573132",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "288",
            "1559",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566381,
          "rowPosition": 566382,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566382\" violates the foreign key: for \"id_documento_viagem\": values \"573132\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573099",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "34",
            "49",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566382,
          "rowPosition": 566383,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566383\" violates the foreign key: for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573099",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "34",
            "49",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566382,
          "rowPosition": 566383,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566383\" violates the foreign key: for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573099",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "8",
            "25",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566383,
          "rowPosition": 566384,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566384\" violates the foreign key: for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573099",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "8",
            "25",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566383,
          "rowPosition": 566384,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566384\" violates the foreign key: for \"id_documento_viagem\": values \"573099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573105",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "40",
            "55",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566386,
          "rowPosition": 566387,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566387\" violates the foreign key: for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573105",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "40",
            "55",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566386,
          "rowPosition": 566387,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566387\" violates the foreign key: for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573105",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "14",
            "31",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566387,
          "rowPosition": 566388,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566388\" violates the foreign key: for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573105",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "14",
            "31",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566387,
          "rowPosition": 566388,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566388\" violates the foreign key: for \"id_documento_viagem\": values \"573105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573129",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "285",
            "1556",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566392,
          "rowPosition": 566393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566393\" violates the foreign key: for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573129",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "285",
            "1556",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566392,
          "rowPosition": 566393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566393\" violates the foreign key: for \"id_documento_viagem\": values \"573129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573124",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "263",
            "1529",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566393,
          "rowPosition": 566394,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566394\" violates the foreign key: for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573124",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "263",
            "1529",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566393,
          "rowPosition": 566394,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566394\" violates the foreign key: for \"id_documento_viagem\": values \"573124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573118",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "62",
            "62",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "163.50"
          ],
          "rowNumber": 566394,
          "rowPosition": 566395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566395\" violates the foreign key: for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573118",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "62",
            "62",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "163.50"
          ],
          "rowNumber": 566394,
          "rowPosition": 566395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566395\" violates the foreign key: for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573118",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "54",
            "54",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "409.50"
          ],
          "rowNumber": 566395,
          "rowPosition": 566396,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566396\" violates the foreign key: for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573118",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "54",
            "54",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "409.50"
          ],
          "rowNumber": 566395,
          "rowPosition": 566396,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566396\" violates the foreign key: for \"id_documento_viagem\": values \"573118\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573119",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "64",
            "64",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "163.50"
          ],
          "rowNumber": 566399,
          "rowPosition": 566400,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566400\" violates the foreign key: for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573119",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "64",
            "64",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "163.50"
          ],
          "rowNumber": 566399,
          "rowPosition": 566400,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566400\" violates the foreign key: for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573119",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "56",
            "56",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "409.50"
          ],
          "rowNumber": 566400,
          "rowPosition": 566401,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566401\" violates the foreign key: for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573119",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "56",
            "56",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "409.50"
          ],
          "rowNumber": 566400,
          "rowPosition": 566401,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566401\" violates the foreign key: for \"id_documento_viagem\": values \"573119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573092",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "56",
            "243",
            "2022-03-04",
            "2022-03-30",
            "0.00",
            "431.07"
          ],
          "rowNumber": 566405,
          "rowPosition": 566406,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566406\" violates the foreign key: for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573092",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "56",
            "243",
            "2022-03-04",
            "2022-03-30",
            "0.00",
            "431.07"
          ],
          "rowNumber": 566405,
          "rowPosition": 566406,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566406\" violates the foreign key: for \"id_documento_viagem\": values \"573092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573122",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "183",
            "295",
            "2022-04-05",
            "2022-04-06",
            "0.00",
            "133.70"
          ],
          "rowNumber": 566407,
          "rowPosition": 566408,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566408\" violates the foreign key: for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573122",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "183",
            "295",
            "2022-04-05",
            "2022-04-06",
            "0.00",
            "133.70"
          ],
          "rowNumber": 566407,
          "rowPosition": 566408,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566408\" violates the foreign key: for \"id_documento_viagem\": values \"573122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573106",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "41",
            "56",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566410,
          "rowPosition": 566411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566411\" violates the foreign key: for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573106",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "41",
            "56",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566410,
          "rowPosition": 566411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566411\" violates the foreign key: for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573106",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "15",
            "32",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566411,
          "rowPosition": 566412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566412\" violates the foreign key: for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573106",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "15",
            "32",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566411,
          "rowPosition": 566412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566412\" violates the foreign key: for \"id_documento_viagem\": values \"573106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573127",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "283",
            "1554",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566415,
          "rowPosition": 566416,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566416\" violates the foreign key: for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573127",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "283",
            "1554",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566415,
          "rowPosition": 566416,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566416\" violates the foreign key: for \"id_documento_viagem\": values \"573127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13213770",
            "14339",
            "1970",
            "6",
            "3012",
            "56567",
            "0",
            "13",
            "218",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "238.76"
          ],
          "rowNumber": 566418,
          "rowPosition": 566419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566419\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13213770",
            "14339",
            "1970",
            "6",
            "3012",
            "56567",
            "0",
            "13",
            "218",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "238.76"
          ],
          "rowNumber": 566418,
          "rowPosition": 566419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566419\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13213770",
            "14339",
            "1970",
            "6",
            "3012",
            "56567",
            "0",
            "11",
            "195",
            "2022-04-04",
            "2022-04-04",
            "0.00",
            "632.62"
          ],
          "rowNumber": 566419,
          "rowPosition": 566420,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566420\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13213770",
            "14339",
            "1970",
            "6",
            "3012",
            "56567",
            "0",
            "11",
            "195",
            "2022-04-04",
            "2022-04-04",
            "0.00",
            "632.62"
          ],
          "rowNumber": 566419,
          "rowPosition": 566420,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566420\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573130",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "286",
            "1557",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566420,
          "rowPosition": 566421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566421\" violates the foreign key: for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573130",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "286",
            "1557",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566420,
          "rowPosition": 566421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566421\" violates the foreign key: for \"id_documento_viagem\": values \"573130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573112",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "46",
            "61",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "169.91"
          ],
          "rowNumber": 566421,
          "rowPosition": 566422,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566422\" violates the foreign key: for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573112",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "46",
            "61",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "169.91"
          ],
          "rowNumber": 566421,
          "rowPosition": 566422,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566422\" violates the foreign key: for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573112",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "25",
            "45",
            "2022-03-21",
            "2022-03-22",
            "0.00",
            "699.19"
          ],
          "rowNumber": 566422,
          "rowPosition": 566423,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566423\" violates the foreign key: for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573112",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "25",
            "45",
            "2022-03-21",
            "2022-03-22",
            "0.00",
            "699.19"
          ],
          "rowNumber": 566422,
          "rowPosition": 566423,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566423\" violates the foreign key: for \"id_documento_viagem\": values \"573112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573090",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "157",
            "270",
            "2022-03-30",
            "2022-04-01",
            "0.00",
            "352.50"
          ],
          "rowNumber": 566423,
          "rowPosition": 566424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566424\" violates the foreign key: for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573090",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "157",
            "270",
            "2022-03-30",
            "2022-04-01",
            "0.00",
            "352.50"
          ],
          "rowNumber": 566423,
          "rowPosition": 566424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566424\" violates the foreign key: for \"id_documento_viagem\": values \"573090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573113",
            "13239551",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "11",
            "11",
            "2022-04-05",
            "2022-04-12",
            "0.00",
            "210.56"
          ],
          "rowNumber": 566424,
          "rowPosition": 566425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566425\" violates the foreign key: for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573113",
            "13239551",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "11",
            "11",
            "2022-04-05",
            "2022-04-12",
            "0.00",
            "210.56"
          ],
          "rowNumber": 566424,
          "rowPosition": 566425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566425\" violates the foreign key: for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573113",
            "13239551",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "6",
            "6",
            "2022-03-23",
            "2022-03-24",
            "0.00",
            "1619.70"
          ],
          "rowNumber": 566425,
          "rowPosition": 566426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566426\" violates the foreign key: for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573113",
            "13239551",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "6",
            "6",
            "2022-03-23",
            "2022-03-24",
            "0.00",
            "1619.70"
          ],
          "rowNumber": 566425,
          "rowPosition": 566426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566426\" violates the foreign key: for \"id_documento_viagem\": values \"573113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573101",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "36",
            "51",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566426,
          "rowPosition": 566427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566427\" violates the foreign key: for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573101",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "36",
            "51",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566426,
          "rowPosition": 566427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566427\" violates the foreign key: for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573101",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "10",
            "27",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566427,
          "rowPosition": 566428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566428\" violates the foreign key: for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573101",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "10",
            "27",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566427,
          "rowPosition": 566428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566428\" violates the foreign key: for \"id_documento_viagem\": values \"573101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573097",
            "13224442",
            "14286",
            "1948",
            "58",
            "3012",
            "56725",
            "0",
            "11",
            "198",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "2190.70"
          ],
          "rowNumber": 566430,
          "rowPosition": 566431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566431\" violates the foreign key: for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573097",
            "13224442",
            "14286",
            "1948",
            "58",
            "3012",
            "56725",
            "0",
            "11",
            "198",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "2190.70"
          ],
          "rowNumber": 566430,
          "rowPosition": 566431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566431\" violates the foreign key: for \"id_documento_viagem\": values \"573097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573128",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "284",
            "1555",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566433,
          "rowPosition": 566434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566434\" violates the foreign key: for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573128",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "284",
            "1555",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566433,
          "rowPosition": 566434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566434\" violates the foreign key: for \"id_documento_viagem\": values \"573128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573109",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "43",
            "58",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "51.37"
          ],
          "rowNumber": 566436,
          "rowPosition": 566437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566437\" violates the foreign key: for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573109",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "43",
            "58",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "51.37"
          ],
          "rowNumber": 566436,
          "rowPosition": 566437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566437\" violates the foreign key: for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573109",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "18",
            "35",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "211.40"
          ],
          "rowNumber": 566437,
          "rowPosition": 566438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566438\" violates the foreign key: for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573109",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "18",
            "35",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "211.40"
          ],
          "rowNumber": 566437,
          "rowPosition": 566438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566438\" violates the foreign key: for \"id_documento_viagem\": values \"573109\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573107",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "42",
            "57",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566442,
          "rowPosition": 566443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566443\" violates the foreign key: for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573107",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "42",
            "57",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566442,
          "rowPosition": 566443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566443\" violates the foreign key: for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573107",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "16",
            "33",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566443,
          "rowPosition": 566444,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566444\" violates the foreign key: for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573107",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "16",
            "33",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566443,
          "rowPosition": 566444,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566444\" violates the foreign key: for \"id_documento_viagem\": values \"573107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573117",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "65",
            "65",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "18.81"
          ],
          "rowNumber": 566450,
          "rowPosition": 566451,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566451\" violates the foreign key: for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573117",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "65",
            "65",
            "2022-04-11",
            "2022-04-12",
            "0.00",
            "18.81"
          ],
          "rowNumber": 566450,
          "rowPosition": 566451,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566451\" violates the foreign key: for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573117",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "57",
            "57",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "144.72"
          ],
          "rowNumber": 566451,
          "rowPosition": 566452,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566452\" violates the foreign key: for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573117",
            "13246939",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "57",
            "57",
            "2022-04-06",
            "2022-04-07",
            "0.00",
            "144.72"
          ],
          "rowNumber": 566451,
          "rowPosition": 566452,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566452\" violates the foreign key: for \"id_documento_viagem\": values \"573117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573120",
            "13216322",
            "14322",
            "1970",
            "49",
            "3012",
            "56744",
            "0",
            "17",
            "322",
            "2022-04-11",
            "2022-04-11",
            "0.00",
            "382.20"
          ],
          "rowNumber": 566454,
          "rowPosition": 566455,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566455\" violates the foreign key: for \"id_documento_viagem\": values \"573120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573120",
            "13216322",
            "14322",
            "1970",
            "49",
            "3012",
            "56744",
            "0",
            "17",
            "322",
            "2022-04-11",
            "2022-04-11",
            "0.00",
            "382.20"
          ],
          "rowNumber": 566454,
          "rowPosition": 566455,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566455\" violates the foreign key: for \"id_documento_viagem\": values \"573120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573095",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "183",
            "761",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "100.32"
          ],
          "rowNumber": 566455,
          "rowPosition": 566456,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566456\" violates the foreign key: for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573095",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "183",
            "761",
            "2022-04-12",
            "2022-04-12",
            "0.00",
            "100.32"
          ],
          "rowNumber": 566455,
          "rowPosition": 566456,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566456\" violates the foreign key: for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573095",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "128",
            "554",
            "2022-03-22",
            "2022-03-22",
            "0.00",
            "711.00"
          ],
          "rowNumber": 566456,
          "rowPosition": 566457,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566457\" violates the foreign key: for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573095",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "128",
            "554",
            "2022-03-22",
            "2022-03-22",
            "0.00",
            "711.00"
          ],
          "rowNumber": 566456,
          "rowPosition": 566457,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566457\" violates the foreign key: for \"id_documento_viagem\": values \"573095\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573108",
            "13303399",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "2",
            "236",
            "2022-03-28",
            "2022-03-29",
            "0.00",
            "678.50"
          ],
          "rowNumber": 566457,
          "rowPosition": 566458,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566458\" violates the foreign key: for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573108",
            "13303399",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "2",
            "236",
            "2022-03-28",
            "2022-03-29",
            "0.00",
            "678.50"
          ],
          "rowNumber": 566457,
          "rowPosition": 566458,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566458\" violates the foreign key: for \"id_documento_viagem\": values \"573108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573114",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "155",
            "601",
            "2022-03-29",
            "2022-03-29",
            "63.00",
            "546.00"
          ],
          "rowNumber": 566462,
          "rowPosition": 566463,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566463\" violates the foreign key: for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573114",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "155",
            "601",
            "2022-03-29",
            "2022-03-29",
            "63.00",
            "546.00"
          ],
          "rowNumber": 566462,
          "rowPosition": 566463,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566463\" violates the foreign key: for \"id_documento_viagem\": values \"573114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573110",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "44",
            "59",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "51.37"
          ],
          "rowNumber": 566463,
          "rowPosition": 566464,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566464\" violates the foreign key: for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573110",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "44",
            "59",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "51.37"
          ],
          "rowNumber": 566463,
          "rowPosition": 566464,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566464\" violates the foreign key: for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573110",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "19",
            "36",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "211.40"
          ],
          "rowNumber": 566464,
          "rowPosition": 566465,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566465\" violates the foreign key: for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573110",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "19",
            "36",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "211.40"
          ],
          "rowNumber": 566464,
          "rowPosition": 566465,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566465\" violates the foreign key: for \"id_documento_viagem\": values \"573110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573126",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "282",
            "1553",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566465,
          "rowPosition": 566466,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566466\" violates the foreign key: for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573126",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "282",
            "1553",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "73.50"
          ],
          "rowNumber": 566465,
          "rowPosition": 566466,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566466\" violates the foreign key: for \"id_documento_viagem\": values \"573126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573103",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "38",
            "53",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566470,
          "rowPosition": 566471,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566471\" violates the foreign key: for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573103",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "38",
            "53",
            "2022-04-06",
            "2022-04-13",
            "0.00",
            "25.94"
          ],
          "rowNumber": 566470,
          "rowPosition": 566471,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566471\" violates the foreign key: for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573103",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "12",
            "29",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566471,
          "rowPosition": 566472,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566472\" violates the foreign key: for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573103",
            "13235657",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "12",
            "29",
            "2022-03-18",
            "2022-03-21",
            "0.00",
            "79.06"
          ],
          "rowNumber": 566471,
          "rowPosition": 566472,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566472\" violates the foreign key: for \"id_documento_viagem\": values \"573103\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573094",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "173",
            "281",
            "2022-04-04",
            "2022-04-05",
            "0.00",
            "241.88"
          ],
          "rowNumber": 566472,
          "rowPosition": 566473,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566473\" violates the foreign key: for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573094",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "173",
            "281",
            "2022-04-04",
            "2022-04-05",
            "0.00",
            "241.88"
          ],
          "rowNumber": 566472,
          "rowPosition": 566473,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566473\" violates the foreign key: for \"id_documento_viagem\": values \"573094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573093",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "178",
            "286",
            "2022-04-04",
            "2022-04-05",
            "0.00",
            "241.88"
          ],
          "rowNumber": 566475,
          "rowPosition": 566476,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566476\" violates the foreign key: for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573093",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "178",
            "286",
            "2022-04-04",
            "2022-04-05",
            "0.00",
            "241.88"
          ],
          "rowNumber": 566475,
          "rowPosition": 566476,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566476\" violates the foreign key: for \"id_documento_viagem\": values \"573093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573091",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "158",
            "271",
            "2022-03-30",
            "2022-04-01",
            "0.00",
            "431.07"
          ],
          "rowNumber": 566478,
          "rowPosition": 566479,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566479\" violates the foreign key: for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573091",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "158",
            "271",
            "2022-03-30",
            "2022-04-01",
            "0.00",
            "431.07"
          ],
          "rowNumber": 566478,
          "rowPosition": 566479,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566479\" violates the foreign key: for \"id_documento_viagem\": values \"573091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573134",
            "13276000",
            "14424",
            "1970",
            "6",
            "3012",
            "56568",
            "0",
            "9",
            "42",
            "2022-04-07",
            "2022-04-07",
            "0.00",
            "136.50"
          ],
          "rowNumber": 566479,
          "rowPosition": 566480,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566480\" violates the foreign key: for \"id_documento_viagem\": values \"573134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573134",
            "13276000",
            "14424",
            "1970",
            "6",
            "3012",
            "56568",
            "0",
            "9",
            "42",
            "2022-04-07",
            "2022-04-07",
            "0.00",
            "136.50"
          ],
          "rowNumber": 566479,
          "rowPosition": 566480,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566480\" violates the foreign key: for \"id_documento_viagem\": values \"573134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573089",
            "13224442",
            "14286",
            "1948",
            "58",
            "3012",
            "56725",
            "0",
            "6",
            "123",
            "2022-03-07",
            "2022-03-08",
            "0.00",
            "189.50"
          ],
          "rowNumber": 566484,
          "rowPosition": 566485,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566485\" violates the foreign key: for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573089",
            "13224442",
            "14286",
            "1948",
            "58",
            "3012",
            "56725",
            "0",
            "6",
            "123",
            "2022-03-07",
            "2022-03-08",
            "0.00",
            "189.50"
          ],
          "rowNumber": 566484,
          "rowPosition": 566485,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566485\" violates the foreign key: for \"id_documento_viagem\": values \"573089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573125",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "281",
            "1552",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566491,
          "rowPosition": 566492,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566492\" violates the foreign key: for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573125",
            "13214009",
            "14305",
            "1948",
            "58",
            "3012",
            "56627",
            "0",
            "281",
            "1552",
            "2022-04-08",
            "2022-04-08",
            "0.00",
            "20.50"
          ],
          "rowNumber": 566491,
          "rowPosition": 566492,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566492\" violates the foreign key: for \"id_documento_viagem\": values \"573125\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13317873",
            "14390",
            "1950",
            "6",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "947.23"
          ],
          "rowNumber": 566492,
          "rowPosition": 566493,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566493\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13317873",
            "14390",
            "1950",
            "6",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "947.23"
          ],
          "rowNumber": 566492,
          "rowPosition": 566493,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566493\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13317873",
            "14390",
            "1950",
            "6",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "971.90"
          ],
          "rowNumber": 566493,
          "rowPosition": 566494,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566494\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "573121",
            "13317873",
            "14390",
            "1950",
            "6",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "971.90"
          ],
          "rowNumber": 566493,
          "rowPosition": 566494,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"566494\" violates the foreign key: for \"id_documento_viagem\": values \"573121\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 146
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 146,
    "tasks": 1
  },
  "valid": false
}